
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Clientes` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Clientes
 * 
 */
export type ClientesModel = runtime.Types.Result.DefaultSelection<Prisma.$ClientesPayload>

export type AggregateClientes = {
  _count: ClientesCountAggregateOutputType | null
  _avg: ClientesAvgAggregateOutputType | null
  _sum: ClientesSumAggregateOutputType | null
  _min: ClientesMinAggregateOutputType | null
  _max: ClientesMaxAggregateOutputType | null
}

export type ClientesAvgAggregateOutputType = {
  idCliente: number | null
  idUsuario: number | null
}

export type ClientesSumAggregateOutputType = {
  idCliente: number | null
  idUsuario: number | null
}

export type ClientesMinAggregateOutputType = {
  idCliente: number | null
  idUsuario: number | null
  nombre: string | null
  email: string | null
  calle: string | null
  numero: string | null
  ciudad: string | null
  provincia: string | null
  codigoPostal: string | null
  pais: string | null
  contacto: string | null
  activo: boolean | null
}

export type ClientesMaxAggregateOutputType = {
  idCliente: number | null
  idUsuario: number | null
  nombre: string | null
  email: string | null
  calle: string | null
  numero: string | null
  ciudad: string | null
  provincia: string | null
  codigoPostal: string | null
  pais: string | null
  contacto: string | null
  activo: boolean | null
}

export type ClientesCountAggregateOutputType = {
  idCliente: number
  idUsuario: number
  nombre: number
  email: number
  calle: number
  numero: number
  ciudad: number
  provincia: number
  codigoPostal: number
  pais: number
  contacto: number
  activo: number
  _all: number
}


export type ClientesAvgAggregateInputType = {
  idCliente?: true
  idUsuario?: true
}

export type ClientesSumAggregateInputType = {
  idCliente?: true
  idUsuario?: true
}

export type ClientesMinAggregateInputType = {
  idCliente?: true
  idUsuario?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
}

export type ClientesMaxAggregateInputType = {
  idCliente?: true
  idUsuario?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
}

export type ClientesCountAggregateInputType = {
  idCliente?: true
  idUsuario?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
  _all?: true
}

export type ClientesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clientes to aggregate.
   */
  where?: Prisma.ClientesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clientes to fetch.
   */
  orderBy?: Prisma.ClientesOrderByWithRelationInput | Prisma.ClientesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ClientesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Clientes
  **/
  _count?: true | ClientesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ClientesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ClientesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ClientesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ClientesMaxAggregateInputType
}

export type GetClientesAggregateType<T extends ClientesAggregateArgs> = {
      [P in keyof T & keyof AggregateClientes]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClientes[P]>
    : Prisma.GetScalarType<T[P], AggregateClientes[P]>
}




export type ClientesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ClientesWhereInput
  orderBy?: Prisma.ClientesOrderByWithAggregationInput | Prisma.ClientesOrderByWithAggregationInput[]
  by: Prisma.ClientesScalarFieldEnum[] | Prisma.ClientesScalarFieldEnum
  having?: Prisma.ClientesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ClientesCountAggregateInputType | true
  _avg?: ClientesAvgAggregateInputType
  _sum?: ClientesSumAggregateInputType
  _min?: ClientesMinAggregateInputType
  _max?: ClientesMaxAggregateInputType
}

export type ClientesGroupByOutputType = {
  idCliente: number
  idUsuario: number
  nombre: string
  email: string | null
  calle: string
  numero: string | null
  ciudad: string
  provincia: string
  codigoPostal: string
  pais: string
  contacto: string | null
  activo: boolean
  _count: ClientesCountAggregateOutputType | null
  _avg: ClientesAvgAggregateOutputType | null
  _sum: ClientesSumAggregateOutputType | null
  _min: ClientesMinAggregateOutputType | null
  _max: ClientesMaxAggregateOutputType | null
}

type GetClientesGroupByPayload<T extends ClientesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ClientesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ClientesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ClientesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ClientesGroupByOutputType[P]>
      }
    >
  >



export type ClientesWhereInput = {
  AND?: Prisma.ClientesWhereInput | Prisma.ClientesWhereInput[]
  OR?: Prisma.ClientesWhereInput[]
  NOT?: Prisma.ClientesWhereInput | Prisma.ClientesWhereInput[]
  idCliente?: Prisma.IntFilter<"Clientes"> | number
  idUsuario?: Prisma.IntFilter<"Clientes"> | number
  nombre?: Prisma.StringFilter<"Clientes"> | string
  email?: Prisma.StringNullableFilter<"Clientes"> | string | null
  calle?: Prisma.StringFilter<"Clientes"> | string
  numero?: Prisma.StringNullableFilter<"Clientes"> | string | null
  ciudad?: Prisma.StringFilter<"Clientes"> | string
  provincia?: Prisma.StringFilter<"Clientes"> | string
  codigoPostal?: Prisma.StringFilter<"Clientes"> | string
  pais?: Prisma.StringFilter<"Clientes"> | string
  contacto?: Prisma.StringNullableFilter<"Clientes"> | string | null
  activo?: Prisma.BoolFilter<"Clientes"> | boolean
  usuario?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
  historial?: Prisma.OperacionesListRelationFilter
}

export type ClientesOrderByWithRelationInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrderInput | Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrderInput | Prisma.SortOrder
  activo?: Prisma.SortOrder
  usuario?: Prisma.UsuariosOrderByWithRelationInput
  historial?: Prisma.OperacionesOrderByRelationAggregateInput
}

export type ClientesWhereUniqueInput = Prisma.AtLeast<{
  idCliente?: number
  idUsuario?: number
  AND?: Prisma.ClientesWhereInput | Prisma.ClientesWhereInput[]
  OR?: Prisma.ClientesWhereInput[]
  NOT?: Prisma.ClientesWhereInput | Prisma.ClientesWhereInput[]
  nombre?: Prisma.StringFilter<"Clientes"> | string
  email?: Prisma.StringNullableFilter<"Clientes"> | string | null
  calle?: Prisma.StringFilter<"Clientes"> | string
  numero?: Prisma.StringNullableFilter<"Clientes"> | string | null
  ciudad?: Prisma.StringFilter<"Clientes"> | string
  provincia?: Prisma.StringFilter<"Clientes"> | string
  codigoPostal?: Prisma.StringFilter<"Clientes"> | string
  pais?: Prisma.StringFilter<"Clientes"> | string
  contacto?: Prisma.StringNullableFilter<"Clientes"> | string | null
  activo?: Prisma.BoolFilter<"Clientes"> | boolean
  usuario?: Prisma.XOR<Prisma.UsuariosScalarRelationFilter, Prisma.UsuariosWhereInput>
  historial?: Prisma.OperacionesListRelationFilter
}, "idCliente" | "idUsuario">

export type ClientesOrderByWithAggregationInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrderInput | Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrderInput | Prisma.SortOrder
  activo?: Prisma.SortOrder
  _count?: Prisma.ClientesCountOrderByAggregateInput
  _avg?: Prisma.ClientesAvgOrderByAggregateInput
  _max?: Prisma.ClientesMaxOrderByAggregateInput
  _min?: Prisma.ClientesMinOrderByAggregateInput
  _sum?: Prisma.ClientesSumOrderByAggregateInput
}

export type ClientesScalarWhereWithAggregatesInput = {
  AND?: Prisma.ClientesScalarWhereWithAggregatesInput | Prisma.ClientesScalarWhereWithAggregatesInput[]
  OR?: Prisma.ClientesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ClientesScalarWhereWithAggregatesInput | Prisma.ClientesScalarWhereWithAggregatesInput[]
  idCliente?: Prisma.IntWithAggregatesFilter<"Clientes"> | number
  idUsuario?: Prisma.IntWithAggregatesFilter<"Clientes"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"Clientes"> | string | null
  calle?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  numero?: Prisma.StringNullableWithAggregatesFilter<"Clientes"> | string | null
  ciudad?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  provincia?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  codigoPostal?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  pais?: Prisma.StringWithAggregatesFilter<"Clientes"> | string
  contacto?: Prisma.StringNullableWithAggregatesFilter<"Clientes"> | string | null
  activo?: Prisma.BoolWithAggregatesFilter<"Clientes"> | boolean
}

export type ClientesCreateInput = {
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
  usuario: Prisma.UsuariosCreateNestedOneWithoutClienteInput
  historial?: Prisma.OperacionesCreateNestedManyWithoutClienteInput
}

export type ClientesUncheckedCreateInput = {
  idCliente?: number
  idUsuario: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
  historial?: Prisma.OperacionesUncheckedCreateNestedManyWithoutClienteInput
}

export type ClientesUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usuario?: Prisma.UsuariosUpdateOneRequiredWithoutClienteNestedInput
  historial?: Prisma.OperacionesUpdateManyWithoutClienteNestedInput
}

export type ClientesUncheckedUpdateInput = {
  idCliente?: Prisma.IntFieldUpdateOperationsInput | number
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  historial?: Prisma.OperacionesUncheckedUpdateManyWithoutClienteNestedInput
}

export type ClientesCreateManyInput = {
  idCliente?: number
  idUsuario: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
}

export type ClientesUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ClientesUncheckedUpdateManyInput = {
  idCliente?: Prisma.IntFieldUpdateOperationsInput | number
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ClientesNullableScalarRelationFilter = {
  is?: Prisma.ClientesWhereInput | null
  isNot?: Prisma.ClientesWhereInput | null
}

export type ClientesCountOrderByAggregateInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type ClientesAvgOrderByAggregateInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
}

export type ClientesMaxOrderByAggregateInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type ClientesMinOrderByAggregateInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type ClientesSumOrderByAggregateInput = {
  idCliente?: Prisma.SortOrder
  idUsuario?: Prisma.SortOrder
}

export type ClientesScalarRelationFilter = {
  is?: Prisma.ClientesWhereInput
  isNot?: Prisma.ClientesWhereInput
}

export type ClientesCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ClientesWhereUniqueInput
}

export type ClientesUncheckedCreateNestedOneWithoutUsuarioInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutUsuarioInput
  connect?: Prisma.ClientesWhereUniqueInput
}

export type ClientesUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ClientesUpsertWithoutUsuarioInput
  disconnect?: Prisma.ClientesWhereInput | boolean
  delete?: Prisma.ClientesWhereInput | boolean
  connect?: Prisma.ClientesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientesUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ClientesUpdateWithoutUsuarioInput>, Prisma.ClientesUncheckedUpdateWithoutUsuarioInput>
}

export type ClientesUncheckedUpdateOneWithoutUsuarioNestedInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutUsuarioInput
  upsert?: Prisma.ClientesUpsertWithoutUsuarioInput
  disconnect?: Prisma.ClientesWhereInput | boolean
  delete?: Prisma.ClientesWhereInput | boolean
  connect?: Prisma.ClientesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientesUpdateToOneWithWhereWithoutUsuarioInput, Prisma.ClientesUpdateWithoutUsuarioInput>, Prisma.ClientesUncheckedUpdateWithoutUsuarioInput>
}

export type ClientesCreateNestedOneWithoutHistorialInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutHistorialInput, Prisma.ClientesUncheckedCreateWithoutHistorialInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutHistorialInput
  connect?: Prisma.ClientesWhereUniqueInput
}

export type ClientesUpdateOneRequiredWithoutHistorialNestedInput = {
  create?: Prisma.XOR<Prisma.ClientesCreateWithoutHistorialInput, Prisma.ClientesUncheckedCreateWithoutHistorialInput>
  connectOrCreate?: Prisma.ClientesCreateOrConnectWithoutHistorialInput
  upsert?: Prisma.ClientesUpsertWithoutHistorialInput
  connect?: Prisma.ClientesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ClientesUpdateToOneWithWhereWithoutHistorialInput, Prisma.ClientesUpdateWithoutHistorialInput>, Prisma.ClientesUncheckedUpdateWithoutHistorialInput>
}

export type ClientesCreateWithoutUsuarioInput = {
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
  historial?: Prisma.OperacionesCreateNestedManyWithoutClienteInput
}

export type ClientesUncheckedCreateWithoutUsuarioInput = {
  idCliente?: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
  historial?: Prisma.OperacionesUncheckedCreateNestedManyWithoutClienteInput
}

export type ClientesCreateOrConnectWithoutUsuarioInput = {
  where: Prisma.ClientesWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
}

export type ClientesUpsertWithoutUsuarioInput = {
  update: Prisma.XOR<Prisma.ClientesUpdateWithoutUsuarioInput, Prisma.ClientesUncheckedUpdateWithoutUsuarioInput>
  create: Prisma.XOR<Prisma.ClientesCreateWithoutUsuarioInput, Prisma.ClientesUncheckedCreateWithoutUsuarioInput>
  where?: Prisma.ClientesWhereInput
}

export type ClientesUpdateToOneWithWhereWithoutUsuarioInput = {
  where?: Prisma.ClientesWhereInput
  data: Prisma.XOR<Prisma.ClientesUpdateWithoutUsuarioInput, Prisma.ClientesUncheckedUpdateWithoutUsuarioInput>
}

export type ClientesUpdateWithoutUsuarioInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  historial?: Prisma.OperacionesUpdateManyWithoutClienteNestedInput
}

export type ClientesUncheckedUpdateWithoutUsuarioInput = {
  idCliente?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  historial?: Prisma.OperacionesUncheckedUpdateManyWithoutClienteNestedInput
}

export type ClientesCreateWithoutHistorialInput = {
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
  usuario: Prisma.UsuariosCreateNestedOneWithoutClienteInput
}

export type ClientesUncheckedCreateWithoutHistorialInput = {
  idCliente?: number
  idUsuario: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
}

export type ClientesCreateOrConnectWithoutHistorialInput = {
  where: Prisma.ClientesWhereUniqueInput
  create: Prisma.XOR<Prisma.ClientesCreateWithoutHistorialInput, Prisma.ClientesUncheckedCreateWithoutHistorialInput>
}

export type ClientesUpsertWithoutHistorialInput = {
  update: Prisma.XOR<Prisma.ClientesUpdateWithoutHistorialInput, Prisma.ClientesUncheckedUpdateWithoutHistorialInput>
  create: Prisma.XOR<Prisma.ClientesCreateWithoutHistorialInput, Prisma.ClientesUncheckedCreateWithoutHistorialInput>
  where?: Prisma.ClientesWhereInput
}

export type ClientesUpdateToOneWithWhereWithoutHistorialInput = {
  where?: Prisma.ClientesWhereInput
  data: Prisma.XOR<Prisma.ClientesUpdateWithoutHistorialInput, Prisma.ClientesUncheckedUpdateWithoutHistorialInput>
}

export type ClientesUpdateWithoutHistorialInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  usuario?: Prisma.UsuariosUpdateOneRequiredWithoutClienteNestedInput
}

export type ClientesUncheckedUpdateWithoutHistorialInput = {
  idCliente?: Prisma.IntFieldUpdateOperationsInput | number
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type ClientesCountOutputType
 */

export type ClientesCountOutputType = {
  historial: number
}

export type ClientesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  historial?: boolean | ClientesCountOutputTypeCountHistorialArgs
}

/**
 * ClientesCountOutputType without action
 */
export type ClientesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ClientesCountOutputType
   */
  select?: Prisma.ClientesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ClientesCountOutputType without action
 */
export type ClientesCountOutputTypeCountHistorialArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OperacionesWhereInput
}


export type ClientesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCliente?: boolean
  idUsuario?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  historial?: boolean | Prisma.Clientes$historialArgs<ExtArgs>
  _count?: boolean | Prisma.ClientesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientes"]>

export type ClientesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCliente?: boolean
  idUsuario?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientes"]>

export type ClientesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idCliente?: boolean
  idUsuario?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}, ExtArgs["result"]["clientes"]>

export type ClientesSelectScalar = {
  idCliente?: boolean
  idUsuario?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
}

export type ClientesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idCliente" | "idUsuario" | "nombre" | "email" | "calle" | "numero" | "ciudad" | "provincia" | "codigoPostal" | "pais" | "contacto" | "activo", ExtArgs["result"]["clientes"]>
export type ClientesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
  historial?: boolean | Prisma.Clientes$historialArgs<ExtArgs>
  _count?: boolean | Prisma.ClientesCountOutputTypeDefaultArgs<ExtArgs>
}
export type ClientesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}
export type ClientesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  usuario?: boolean | Prisma.UsuariosDefaultArgs<ExtArgs>
}

export type $ClientesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Clientes"
  objects: {
    usuario: Prisma.$UsuariosPayload<ExtArgs>
    historial: Prisma.$OperacionesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idCliente: number
    idUsuario: number
    nombre: string
    email: string | null
    calle: string
    numero: string | null
    ciudad: string
    provincia: string
    codigoPostal: string
    pais: string
    contacto: string | null
    activo: boolean
  }, ExtArgs["result"]["clientes"]>
  composites: {}
}

export type ClientesGetPayload<S extends boolean | null | undefined | ClientesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ClientesPayload, S>

export type ClientesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ClientesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ClientesCountAggregateInputType | true
  }

export interface ClientesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Clientes'], meta: { name: 'Clientes' } }
  /**
   * Find zero or one Clientes that matches the filter.
   * @param {ClientesFindUniqueArgs} args - Arguments to find a Clientes
   * @example
   * // Get one Clientes
   * const clientes = await prisma.clientes.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ClientesFindUniqueArgs>(args: Prisma.SelectSubset<T, ClientesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Clientes that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ClientesFindUniqueOrThrowArgs} args - Arguments to find a Clientes
   * @example
   * // Get one Clientes
   * const clientes = await prisma.clientes.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ClientesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ClientesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clientes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesFindFirstArgs} args - Arguments to find a Clientes
   * @example
   * // Get one Clientes
   * const clientes = await prisma.clientes.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ClientesFindFirstArgs>(args?: Prisma.SelectSubset<T, ClientesFindFirstArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Clientes that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesFindFirstOrThrowArgs} args - Arguments to find a Clientes
   * @example
   * // Get one Clientes
   * const clientes = await prisma.clientes.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ClientesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ClientesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Clientes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Clientes
   * const clientes = await prisma.clientes.findMany()
   * 
   * // Get first 10 Clientes
   * const clientes = await prisma.clientes.findMany({ take: 10 })
   * 
   * // Only select the `idCliente`
   * const clientesWithIdClienteOnly = await prisma.clientes.findMany({ select: { idCliente: true } })
   * 
   */
  findMany<T extends ClientesFindManyArgs>(args?: Prisma.SelectSubset<T, ClientesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Clientes.
   * @param {ClientesCreateArgs} args - Arguments to create a Clientes.
   * @example
   * // Create one Clientes
   * const Clientes = await prisma.clientes.create({
   *   data: {
   *     // ... data to create a Clientes
   *   }
   * })
   * 
   */
  create<T extends ClientesCreateArgs>(args: Prisma.SelectSubset<T, ClientesCreateArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Clientes.
   * @param {ClientesCreateManyArgs} args - Arguments to create many Clientes.
   * @example
   * // Create many Clientes
   * const clientes = await prisma.clientes.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ClientesCreateManyArgs>(args?: Prisma.SelectSubset<T, ClientesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Clientes and returns the data saved in the database.
   * @param {ClientesCreateManyAndReturnArgs} args - Arguments to create many Clientes.
   * @example
   * // Create many Clientes
   * const clientes = await prisma.clientes.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Clientes and only return the `idCliente`
   * const clientesWithIdClienteOnly = await prisma.clientes.createManyAndReturn({
   *   select: { idCliente: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ClientesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ClientesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Clientes.
   * @param {ClientesDeleteArgs} args - Arguments to delete one Clientes.
   * @example
   * // Delete one Clientes
   * const Clientes = await prisma.clientes.delete({
   *   where: {
   *     // ... filter to delete one Clientes
   *   }
   * })
   * 
   */
  delete<T extends ClientesDeleteArgs>(args: Prisma.SelectSubset<T, ClientesDeleteArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Clientes.
   * @param {ClientesUpdateArgs} args - Arguments to update one Clientes.
   * @example
   * // Update one Clientes
   * const clientes = await prisma.clientes.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ClientesUpdateArgs>(args: Prisma.SelectSubset<T, ClientesUpdateArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Clientes.
   * @param {ClientesDeleteManyArgs} args - Arguments to filter Clientes to delete.
   * @example
   * // Delete a few Clientes
   * const { count } = await prisma.clientes.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ClientesDeleteManyArgs>(args?: Prisma.SelectSubset<T, ClientesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Clientes
   * const clientes = await prisma.clientes.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ClientesUpdateManyArgs>(args: Prisma.SelectSubset<T, ClientesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Clientes and returns the data updated in the database.
   * @param {ClientesUpdateManyAndReturnArgs} args - Arguments to update many Clientes.
   * @example
   * // Update many Clientes
   * const clientes = await prisma.clientes.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Clientes and only return the `idCliente`
   * const clientesWithIdClienteOnly = await prisma.clientes.updateManyAndReturn({
   *   select: { idCliente: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ClientesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ClientesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Clientes.
   * @param {ClientesUpsertArgs} args - Arguments to update or create a Clientes.
   * @example
   * // Update or create a Clientes
   * const clientes = await prisma.clientes.upsert({
   *   create: {
   *     // ... data to create a Clientes
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Clientes we want to update
   *   }
   * })
   */
  upsert<T extends ClientesUpsertArgs>(args: Prisma.SelectSubset<T, ClientesUpsertArgs<ExtArgs>>): Prisma.Prisma__ClientesClient<runtime.Types.Result.GetResult<Prisma.$ClientesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Clientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesCountArgs} args - Arguments to filter Clientes to count.
   * @example
   * // Count the number of Clientes
   * const count = await prisma.clientes.count({
   *   where: {
   *     // ... the filter for the Clientes we want to count
   *   }
   * })
  **/
  count<T extends ClientesCountArgs>(
    args?: Prisma.Subset<T, ClientesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ClientesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Clientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ClientesAggregateArgs>(args: Prisma.Subset<T, ClientesAggregateArgs>): Prisma.PrismaPromise<GetClientesAggregateType<T>>

  /**
   * Group by Clientes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ClientesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ClientesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ClientesGroupByArgs['orderBy'] }
      : { orderBy?: ClientesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ClientesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClientesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Clientes model
 */
readonly fields: ClientesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Clientes.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ClientesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  usuario<T extends Prisma.UsuariosDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UsuariosDefaultArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  historial<T extends Prisma.Clientes$historialArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Clientes$historialArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OperacionesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Clientes model
 */
export interface ClientesFieldRefs {
  readonly idCliente: Prisma.FieldRef<"Clientes", 'Int'>
  readonly idUsuario: Prisma.FieldRef<"Clientes", 'Int'>
  readonly nombre: Prisma.FieldRef<"Clientes", 'String'>
  readonly email: Prisma.FieldRef<"Clientes", 'String'>
  readonly calle: Prisma.FieldRef<"Clientes", 'String'>
  readonly numero: Prisma.FieldRef<"Clientes", 'String'>
  readonly ciudad: Prisma.FieldRef<"Clientes", 'String'>
  readonly provincia: Prisma.FieldRef<"Clientes", 'String'>
  readonly codigoPostal: Prisma.FieldRef<"Clientes", 'String'>
  readonly pais: Prisma.FieldRef<"Clientes", 'String'>
  readonly contacto: Prisma.FieldRef<"Clientes", 'String'>
  readonly activo: Prisma.FieldRef<"Clientes", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Clientes findUnique
 */
export type ClientesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter, which Clientes to fetch.
   */
  where: Prisma.ClientesWhereUniqueInput
}

/**
 * Clientes findUniqueOrThrow
 */
export type ClientesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter, which Clientes to fetch.
   */
  where: Prisma.ClientesWhereUniqueInput
}

/**
 * Clientes findFirst
 */
export type ClientesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter, which Clientes to fetch.
   */
  where?: Prisma.ClientesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clientes to fetch.
   */
  orderBy?: Prisma.ClientesOrderByWithRelationInput | Prisma.ClientesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clientes.
   */
  cursor?: Prisma.ClientesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clientes.
   */
  distinct?: Prisma.ClientesScalarFieldEnum | Prisma.ClientesScalarFieldEnum[]
}

/**
 * Clientes findFirstOrThrow
 */
export type ClientesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter, which Clientes to fetch.
   */
  where?: Prisma.ClientesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clientes to fetch.
   */
  orderBy?: Prisma.ClientesOrderByWithRelationInput | Prisma.ClientesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Clientes.
   */
  cursor?: Prisma.ClientesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clientes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Clientes.
   */
  distinct?: Prisma.ClientesScalarFieldEnum | Prisma.ClientesScalarFieldEnum[]
}

/**
 * Clientes findMany
 */
export type ClientesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter, which Clientes to fetch.
   */
  where?: Prisma.ClientesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Clientes to fetch.
   */
  orderBy?: Prisma.ClientesOrderByWithRelationInput | Prisma.ClientesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Clientes.
   */
  cursor?: Prisma.ClientesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Clientes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Clientes.
   */
  skip?: number
  distinct?: Prisma.ClientesScalarFieldEnum | Prisma.ClientesScalarFieldEnum[]
}

/**
 * Clientes create
 */
export type ClientesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * The data needed to create a Clientes.
   */
  data: Prisma.XOR<Prisma.ClientesCreateInput, Prisma.ClientesUncheckedCreateInput>
}

/**
 * Clientes createMany
 */
export type ClientesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Clientes.
   */
  data: Prisma.ClientesCreateManyInput | Prisma.ClientesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Clientes createManyAndReturn
 */
export type ClientesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * The data used to create many Clientes.
   */
  data: Prisma.ClientesCreateManyInput | Prisma.ClientesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Clientes update
 */
export type ClientesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * The data needed to update a Clientes.
   */
  data: Prisma.XOR<Prisma.ClientesUpdateInput, Prisma.ClientesUncheckedUpdateInput>
  /**
   * Choose, which Clientes to update.
   */
  where: Prisma.ClientesWhereUniqueInput
}

/**
 * Clientes updateMany
 */
export type ClientesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Clientes.
   */
  data: Prisma.XOR<Prisma.ClientesUpdateManyMutationInput, Prisma.ClientesUncheckedUpdateManyInput>
  /**
   * Filter which Clientes to update
   */
  where?: Prisma.ClientesWhereInput
  /**
   * Limit how many Clientes to update.
   */
  limit?: number
}

/**
 * Clientes updateManyAndReturn
 */
export type ClientesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * The data used to update Clientes.
   */
  data: Prisma.XOR<Prisma.ClientesUpdateManyMutationInput, Prisma.ClientesUncheckedUpdateManyInput>
  /**
   * Filter which Clientes to update
   */
  where?: Prisma.ClientesWhereInput
  /**
   * Limit how many Clientes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Clientes upsert
 */
export type ClientesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * The filter to search for the Clientes to update in case it exists.
   */
  where: Prisma.ClientesWhereUniqueInput
  /**
   * In case the Clientes found by the `where` argument doesn't exist, create a new Clientes with this data.
   */
  create: Prisma.XOR<Prisma.ClientesCreateInput, Prisma.ClientesUncheckedCreateInput>
  /**
   * In case the Clientes was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ClientesUpdateInput, Prisma.ClientesUncheckedUpdateInput>
}

/**
 * Clientes delete
 */
export type ClientesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
  /**
   * Filter which Clientes to delete.
   */
  where: Prisma.ClientesWhereUniqueInput
}

/**
 * Clientes deleteMany
 */
export type ClientesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Clientes to delete
   */
  where?: Prisma.ClientesWhereInput
  /**
   * Limit how many Clientes to delete.
   */
  limit?: number
}

/**
 * Clientes.historial
 */
export type Clientes$historialArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Operaciones
   */
  select?: Prisma.OperacionesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Operaciones
   */
  omit?: Prisma.OperacionesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OperacionesInclude<ExtArgs> | null
  where?: Prisma.OperacionesWhereInput
  orderBy?: Prisma.OperacionesOrderByWithRelationInput | Prisma.OperacionesOrderByWithRelationInput[]
  cursor?: Prisma.OperacionesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OperacionesScalarFieldEnum | Prisma.OperacionesScalarFieldEnum[]
}

/**
 * Clientes without action
 */
export type ClientesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Clientes
   */
  select?: Prisma.ClientesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Clientes
   */
  omit?: Prisma.ClientesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ClientesInclude<ExtArgs> | null
}
