
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Comanda` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Comanda
 * 
 */
export type ComandaModel = runtime.Types.Result.DefaultSelection<Prisma.$ComandaPayload>

export type AggregateComanda = {
  _count: ComandaCountAggregateOutputType | null
  _avg: ComandaAvgAggregateOutputType | null
  _sum: ComandaSumAggregateOutputType | null
  _min: ComandaMinAggregateOutputType | null
  _max: ComandaMaxAggregateOutputType | null
}

export type ComandaAvgAggregateOutputType = {
  id: number | null
  idOperacion: number | null
}

export type ComandaSumAggregateOutputType = {
  id: number | null
  idOperacion: number | null
}

export type ComandaMinAggregateOutputType = {
  id: number | null
  idOperacion: number | null
  estado: $Enums.EstadoComanda | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ComandaMaxAggregateOutputType = {
  id: number | null
  idOperacion: number | null
  estado: $Enums.EstadoComanda | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ComandaCountAggregateOutputType = {
  id: number
  idOperacion: number
  estado: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ComandaAvgAggregateInputType = {
  id?: true
  idOperacion?: true
}

export type ComandaSumAggregateInputType = {
  id?: true
  idOperacion?: true
}

export type ComandaMinAggregateInputType = {
  id?: true
  idOperacion?: true
  estado?: true
  createdAt?: true
  updatedAt?: true
}

export type ComandaMaxAggregateInputType = {
  id?: true
  idOperacion?: true
  estado?: true
  createdAt?: true
  updatedAt?: true
}

export type ComandaCountAggregateInputType = {
  id?: true
  idOperacion?: true
  estado?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ComandaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Comanda to aggregate.
   */
  where?: Prisma.ComandaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Comandas to fetch.
   */
  orderBy?: Prisma.ComandaOrderByWithRelationInput | Prisma.ComandaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ComandaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Comandas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Comandas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Comandas
  **/
  _count?: true | ComandaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ComandaAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ComandaSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ComandaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ComandaMaxAggregateInputType
}

export type GetComandaAggregateType<T extends ComandaAggregateArgs> = {
      [P in keyof T & keyof AggregateComanda]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateComanda[P]>
    : Prisma.GetScalarType<T[P], AggregateComanda[P]>
}




export type ComandaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ComandaWhereInput
  orderBy?: Prisma.ComandaOrderByWithAggregationInput | Prisma.ComandaOrderByWithAggregationInput[]
  by: Prisma.ComandaScalarFieldEnum[] | Prisma.ComandaScalarFieldEnum
  having?: Prisma.ComandaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ComandaCountAggregateInputType | true
  _avg?: ComandaAvgAggregateInputType
  _sum?: ComandaSumAggregateInputType
  _min?: ComandaMinAggregateInputType
  _max?: ComandaMaxAggregateInputType
}

export type ComandaGroupByOutputType = {
  id: number
  idOperacion: number
  estado: $Enums.EstadoComanda
  createdAt: Date
  updatedAt: Date
  _count: ComandaCountAggregateOutputType | null
  _avg: ComandaAvgAggregateOutputType | null
  _sum: ComandaSumAggregateOutputType | null
  _min: ComandaMinAggregateOutputType | null
  _max: ComandaMaxAggregateOutputType | null
}

type GetComandaGroupByPayload<T extends ComandaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ComandaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ComandaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ComandaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ComandaGroupByOutputType[P]>
      }
    >
  >



export type ComandaWhereInput = {
  AND?: Prisma.ComandaWhereInput | Prisma.ComandaWhereInput[]
  OR?: Prisma.ComandaWhereInput[]
  NOT?: Prisma.ComandaWhereInput | Prisma.ComandaWhereInput[]
  id?: Prisma.IntFilter<"Comanda"> | number
  idOperacion?: Prisma.IntFilter<"Comanda"> | number
  estado?: Prisma.EnumEstadoComandaFilter<"Comanda"> | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFilter<"Comanda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Comanda"> | Date | string
  operacion?: Prisma.XOR<Prisma.OperacionesScalarRelationFilter, Prisma.OperacionesWhereInput>
  productos?: Prisma.ComandaProductosListRelationFilter
}

export type ComandaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  operacion?: Prisma.OperacionesOrderByWithRelationInput
  productos?: Prisma.ComandaProductosOrderByRelationAggregateInput
}

export type ComandaWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  idOperacion?: number
  AND?: Prisma.ComandaWhereInput | Prisma.ComandaWhereInput[]
  OR?: Prisma.ComandaWhereInput[]
  NOT?: Prisma.ComandaWhereInput | Prisma.ComandaWhereInput[]
  estado?: Prisma.EnumEstadoComandaFilter<"Comanda"> | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFilter<"Comanda"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Comanda"> | Date | string
  operacion?: Prisma.XOR<Prisma.OperacionesScalarRelationFilter, Prisma.OperacionesWhereInput>
  productos?: Prisma.ComandaProductosListRelationFilter
}, "id" | "idOperacion">

export type ComandaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ComandaCountOrderByAggregateInput
  _avg?: Prisma.ComandaAvgOrderByAggregateInput
  _max?: Prisma.ComandaMaxOrderByAggregateInput
  _min?: Prisma.ComandaMinOrderByAggregateInput
  _sum?: Prisma.ComandaSumOrderByAggregateInput
}

export type ComandaScalarWhereWithAggregatesInput = {
  AND?: Prisma.ComandaScalarWhereWithAggregatesInput | Prisma.ComandaScalarWhereWithAggregatesInput[]
  OR?: Prisma.ComandaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ComandaScalarWhereWithAggregatesInput | Prisma.ComandaScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Comanda"> | number
  idOperacion?: Prisma.IntWithAggregatesFilter<"Comanda"> | number
  estado?: Prisma.EnumEstadoComandaWithAggregatesFilter<"Comanda"> | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Comanda"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Comanda"> | Date | string
}

export type ComandaCreateInput = {
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
  operacion: Prisma.OperacionesCreateNestedOneWithoutComandaInput
  productos?: Prisma.ComandaProductosCreateNestedManyWithoutComandaInput
}

export type ComandaUncheckedCreateInput = {
  id?: number
  idOperacion: number
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ComandaProductosUncheckedCreateNestedManyWithoutComandaInput
}

export type ComandaUpdateInput = {
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operacion?: Prisma.OperacionesUpdateOneRequiredWithoutComandaNestedInput
  productos?: Prisma.ComandaProductosUpdateManyWithoutComandaNestedInput
}

export type ComandaUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  idOperacion?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ComandaProductosUncheckedUpdateManyWithoutComandaNestedInput
}

export type ComandaCreateManyInput = {
  id?: number
  idOperacion: number
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ComandaUpdateManyMutationInput = {
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComandaUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  idOperacion?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ComandaNullableScalarRelationFilter = {
  is?: Prisma.ComandaWhereInput | null
  isNot?: Prisma.ComandaWhereInput | null
}

export type ComandaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComandaAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
}

export type ComandaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComandaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ComandaSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  idOperacion?: Prisma.SortOrder
}

export type ComandaScalarRelationFilter = {
  is?: Prisma.ComandaWhereInput
  isNot?: Prisma.ComandaWhereInput
}

export type ComandaCreateNestedOneWithoutOperacionInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutOperacionInput
  connect?: Prisma.ComandaWhereUniqueInput
}

export type ComandaUncheckedCreateNestedOneWithoutOperacionInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutOperacionInput
  connect?: Prisma.ComandaWhereUniqueInput
}

export type ComandaUpdateOneWithoutOperacionNestedInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutOperacionInput
  upsert?: Prisma.ComandaUpsertWithoutOperacionInput
  disconnect?: Prisma.ComandaWhereInput | boolean
  delete?: Prisma.ComandaWhereInput | boolean
  connect?: Prisma.ComandaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ComandaUpdateToOneWithWhereWithoutOperacionInput, Prisma.ComandaUpdateWithoutOperacionInput>, Prisma.ComandaUncheckedUpdateWithoutOperacionInput>
}

export type ComandaUncheckedUpdateOneWithoutOperacionNestedInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutOperacionInput
  upsert?: Prisma.ComandaUpsertWithoutOperacionInput
  disconnect?: Prisma.ComandaWhereInput | boolean
  delete?: Prisma.ComandaWhereInput | boolean
  connect?: Prisma.ComandaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ComandaUpdateToOneWithWhereWithoutOperacionInput, Prisma.ComandaUpdateWithoutOperacionInput>, Prisma.ComandaUncheckedUpdateWithoutOperacionInput>
}

export type EnumEstadoComandaFieldUpdateOperationsInput = {
  set?: $Enums.EstadoComanda
}

export type ComandaCreateNestedOneWithoutProductosInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutProductosInput, Prisma.ComandaUncheckedCreateWithoutProductosInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutProductosInput
  connect?: Prisma.ComandaWhereUniqueInput
}

export type ComandaUpdateOneRequiredWithoutProductosNestedInput = {
  create?: Prisma.XOR<Prisma.ComandaCreateWithoutProductosInput, Prisma.ComandaUncheckedCreateWithoutProductosInput>
  connectOrCreate?: Prisma.ComandaCreateOrConnectWithoutProductosInput
  upsert?: Prisma.ComandaUpsertWithoutProductosInput
  connect?: Prisma.ComandaWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ComandaUpdateToOneWithWhereWithoutProductosInput, Prisma.ComandaUpdateWithoutProductosInput>, Prisma.ComandaUncheckedUpdateWithoutProductosInput>
}

export type ComandaCreateWithoutOperacionInput = {
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ComandaProductosCreateNestedManyWithoutComandaInput
}

export type ComandaUncheckedCreateWithoutOperacionInput = {
  id?: number
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
  productos?: Prisma.ComandaProductosUncheckedCreateNestedManyWithoutComandaInput
}

export type ComandaCreateOrConnectWithoutOperacionInput = {
  where: Prisma.ComandaWhereUniqueInput
  create: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
}

export type ComandaUpsertWithoutOperacionInput = {
  update: Prisma.XOR<Prisma.ComandaUpdateWithoutOperacionInput, Prisma.ComandaUncheckedUpdateWithoutOperacionInput>
  create: Prisma.XOR<Prisma.ComandaCreateWithoutOperacionInput, Prisma.ComandaUncheckedCreateWithoutOperacionInput>
  where?: Prisma.ComandaWhereInput
}

export type ComandaUpdateToOneWithWhereWithoutOperacionInput = {
  where?: Prisma.ComandaWhereInput
  data: Prisma.XOR<Prisma.ComandaUpdateWithoutOperacionInput, Prisma.ComandaUncheckedUpdateWithoutOperacionInput>
}

export type ComandaUpdateWithoutOperacionInput = {
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ComandaProductosUpdateManyWithoutComandaNestedInput
}

export type ComandaUncheckedUpdateWithoutOperacionInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  productos?: Prisma.ComandaProductosUncheckedUpdateManyWithoutComandaNestedInput
}

export type ComandaCreateWithoutProductosInput = {
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
  operacion: Prisma.OperacionesCreateNestedOneWithoutComandaInput
}

export type ComandaUncheckedCreateWithoutProductosInput = {
  id?: number
  idOperacion: number
  estado?: $Enums.EstadoComanda
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ComandaCreateOrConnectWithoutProductosInput = {
  where: Prisma.ComandaWhereUniqueInput
  create: Prisma.XOR<Prisma.ComandaCreateWithoutProductosInput, Prisma.ComandaUncheckedCreateWithoutProductosInput>
}

export type ComandaUpsertWithoutProductosInput = {
  update: Prisma.XOR<Prisma.ComandaUpdateWithoutProductosInput, Prisma.ComandaUncheckedUpdateWithoutProductosInput>
  create: Prisma.XOR<Prisma.ComandaCreateWithoutProductosInput, Prisma.ComandaUncheckedCreateWithoutProductosInput>
  where?: Prisma.ComandaWhereInput
}

export type ComandaUpdateToOneWithWhereWithoutProductosInput = {
  where?: Prisma.ComandaWhereInput
  data: Prisma.XOR<Prisma.ComandaUpdateWithoutProductosInput, Prisma.ComandaUncheckedUpdateWithoutProductosInput>
}

export type ComandaUpdateWithoutProductosInput = {
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  operacion?: Prisma.OperacionesUpdateOneRequiredWithoutComandaNestedInput
}

export type ComandaUncheckedUpdateWithoutProductosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  idOperacion?: Prisma.IntFieldUpdateOperationsInput | number
  estado?: Prisma.EnumEstadoComandaFieldUpdateOperationsInput | $Enums.EstadoComanda
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ComandaCountOutputType
 */

export type ComandaCountOutputType = {
  productos: number
}

export type ComandaCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  productos?: boolean | ComandaCountOutputTypeCountProductosArgs
}

/**
 * ComandaCountOutputType without action
 */
export type ComandaCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComandaCountOutputType
   */
  select?: Prisma.ComandaCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ComandaCountOutputType without action
 */
export type ComandaCountOutputTypeCountProductosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ComandaProductosWhereInput
}


export type ComandaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idOperacion?: boolean
  estado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
  productos?: boolean | Prisma.Comanda$productosArgs<ExtArgs>
  _count?: boolean | Prisma.ComandaCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comanda"]>

export type ComandaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idOperacion?: boolean
  estado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comanda"]>

export type ComandaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  idOperacion?: boolean
  estado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["comanda"]>

export type ComandaSelectScalar = {
  id?: boolean
  idOperacion?: boolean
  estado?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ComandaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "idOperacion" | "estado" | "createdAt" | "updatedAt", ExtArgs["result"]["comanda"]>
export type ComandaInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
  productos?: boolean | Prisma.Comanda$productosArgs<ExtArgs>
  _count?: boolean | Prisma.ComandaCountOutputTypeDefaultArgs<ExtArgs>
}
export type ComandaIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
}
export type ComandaIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  operacion?: boolean | Prisma.OperacionesDefaultArgs<ExtArgs>
}

export type $ComandaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Comanda"
  objects: {
    operacion: Prisma.$OperacionesPayload<ExtArgs>
    productos: Prisma.$ComandaProductosPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    idOperacion: number
    estado: $Enums.EstadoComanda
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["comanda"]>
  composites: {}
}

export type ComandaGetPayload<S extends boolean | null | undefined | ComandaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ComandaPayload, S>

export type ComandaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ComandaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ComandaCountAggregateInputType | true
  }

export interface ComandaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Comanda'], meta: { name: 'Comanda' } }
  /**
   * Find zero or one Comanda that matches the filter.
   * @param {ComandaFindUniqueArgs} args - Arguments to find a Comanda
   * @example
   * // Get one Comanda
   * const comanda = await prisma.comanda.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ComandaFindUniqueArgs>(args: Prisma.SelectSubset<T, ComandaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Comanda that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ComandaFindUniqueOrThrowArgs} args - Arguments to find a Comanda
   * @example
   * // Get one Comanda
   * const comanda = await prisma.comanda.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ComandaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ComandaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Comanda that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaFindFirstArgs} args - Arguments to find a Comanda
   * @example
   * // Get one Comanda
   * const comanda = await prisma.comanda.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ComandaFindFirstArgs>(args?: Prisma.SelectSubset<T, ComandaFindFirstArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Comanda that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaFindFirstOrThrowArgs} args - Arguments to find a Comanda
   * @example
   * // Get one Comanda
   * const comanda = await prisma.comanda.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ComandaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ComandaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Comandas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Comandas
   * const comandas = await prisma.comanda.findMany()
   * 
   * // Get first 10 Comandas
   * const comandas = await prisma.comanda.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const comandaWithIdOnly = await prisma.comanda.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ComandaFindManyArgs>(args?: Prisma.SelectSubset<T, ComandaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Comanda.
   * @param {ComandaCreateArgs} args - Arguments to create a Comanda.
   * @example
   * // Create one Comanda
   * const Comanda = await prisma.comanda.create({
   *   data: {
   *     // ... data to create a Comanda
   *   }
   * })
   * 
   */
  create<T extends ComandaCreateArgs>(args: Prisma.SelectSubset<T, ComandaCreateArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Comandas.
   * @param {ComandaCreateManyArgs} args - Arguments to create many Comandas.
   * @example
   * // Create many Comandas
   * const comanda = await prisma.comanda.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ComandaCreateManyArgs>(args?: Prisma.SelectSubset<T, ComandaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Comandas and returns the data saved in the database.
   * @param {ComandaCreateManyAndReturnArgs} args - Arguments to create many Comandas.
   * @example
   * // Create many Comandas
   * const comanda = await prisma.comanda.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Comandas and only return the `id`
   * const comandaWithIdOnly = await prisma.comanda.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ComandaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ComandaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Comanda.
   * @param {ComandaDeleteArgs} args - Arguments to delete one Comanda.
   * @example
   * // Delete one Comanda
   * const Comanda = await prisma.comanda.delete({
   *   where: {
   *     // ... filter to delete one Comanda
   *   }
   * })
   * 
   */
  delete<T extends ComandaDeleteArgs>(args: Prisma.SelectSubset<T, ComandaDeleteArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Comanda.
   * @param {ComandaUpdateArgs} args - Arguments to update one Comanda.
   * @example
   * // Update one Comanda
   * const comanda = await prisma.comanda.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ComandaUpdateArgs>(args: Prisma.SelectSubset<T, ComandaUpdateArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Comandas.
   * @param {ComandaDeleteManyArgs} args - Arguments to filter Comandas to delete.
   * @example
   * // Delete a few Comandas
   * const { count } = await prisma.comanda.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ComandaDeleteManyArgs>(args?: Prisma.SelectSubset<T, ComandaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Comandas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Comandas
   * const comanda = await prisma.comanda.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ComandaUpdateManyArgs>(args: Prisma.SelectSubset<T, ComandaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Comandas and returns the data updated in the database.
   * @param {ComandaUpdateManyAndReturnArgs} args - Arguments to update many Comandas.
   * @example
   * // Update many Comandas
   * const comanda = await prisma.comanda.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Comandas and only return the `id`
   * const comandaWithIdOnly = await prisma.comanda.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ComandaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ComandaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Comanda.
   * @param {ComandaUpsertArgs} args - Arguments to update or create a Comanda.
   * @example
   * // Update or create a Comanda
   * const comanda = await prisma.comanda.upsert({
   *   create: {
   *     // ... data to create a Comanda
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Comanda we want to update
   *   }
   * })
   */
  upsert<T extends ComandaUpsertArgs>(args: Prisma.SelectSubset<T, ComandaUpsertArgs<ExtArgs>>): Prisma.Prisma__ComandaClient<runtime.Types.Result.GetResult<Prisma.$ComandaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Comandas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaCountArgs} args - Arguments to filter Comandas to count.
   * @example
   * // Count the number of Comandas
   * const count = await prisma.comanda.count({
   *   where: {
   *     // ... the filter for the Comandas we want to count
   *   }
   * })
  **/
  count<T extends ComandaCountArgs>(
    args?: Prisma.Subset<T, ComandaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ComandaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Comanda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ComandaAggregateArgs>(args: Prisma.Subset<T, ComandaAggregateArgs>): Prisma.PrismaPromise<GetComandaAggregateType<T>>

  /**
   * Group by Comanda.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ComandaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ComandaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ComandaGroupByArgs['orderBy'] }
      : { orderBy?: ComandaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ComandaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetComandaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Comanda model
 */
readonly fields: ComandaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Comanda.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ComandaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  operacion<T extends Prisma.OperacionesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OperacionesDefaultArgs<ExtArgs>>): Prisma.Prisma__OperacionesClient<runtime.Types.Result.GetResult<Prisma.$OperacionesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  productos<T extends Prisma.Comanda$productosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Comanda$productosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ComandaProductosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Comanda model
 */
export interface ComandaFieldRefs {
  readonly id: Prisma.FieldRef<"Comanda", 'Int'>
  readonly idOperacion: Prisma.FieldRef<"Comanda", 'Int'>
  readonly estado: Prisma.FieldRef<"Comanda", 'EstadoComanda'>
  readonly createdAt: Prisma.FieldRef<"Comanda", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Comanda", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Comanda findUnique
 */
export type ComandaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter, which Comanda to fetch.
   */
  where: Prisma.ComandaWhereUniqueInput
}

/**
 * Comanda findUniqueOrThrow
 */
export type ComandaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter, which Comanda to fetch.
   */
  where: Prisma.ComandaWhereUniqueInput
}

/**
 * Comanda findFirst
 */
export type ComandaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter, which Comanda to fetch.
   */
  where?: Prisma.ComandaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Comandas to fetch.
   */
  orderBy?: Prisma.ComandaOrderByWithRelationInput | Prisma.ComandaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Comandas.
   */
  cursor?: Prisma.ComandaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Comandas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Comandas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Comandas.
   */
  distinct?: Prisma.ComandaScalarFieldEnum | Prisma.ComandaScalarFieldEnum[]
}

/**
 * Comanda findFirstOrThrow
 */
export type ComandaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter, which Comanda to fetch.
   */
  where?: Prisma.ComandaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Comandas to fetch.
   */
  orderBy?: Prisma.ComandaOrderByWithRelationInput | Prisma.ComandaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Comandas.
   */
  cursor?: Prisma.ComandaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Comandas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Comandas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Comandas.
   */
  distinct?: Prisma.ComandaScalarFieldEnum | Prisma.ComandaScalarFieldEnum[]
}

/**
 * Comanda findMany
 */
export type ComandaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter, which Comandas to fetch.
   */
  where?: Prisma.ComandaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Comandas to fetch.
   */
  orderBy?: Prisma.ComandaOrderByWithRelationInput | Prisma.ComandaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Comandas.
   */
  cursor?: Prisma.ComandaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Comandas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Comandas.
   */
  skip?: number
  distinct?: Prisma.ComandaScalarFieldEnum | Prisma.ComandaScalarFieldEnum[]
}

/**
 * Comanda create
 */
export type ComandaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * The data needed to create a Comanda.
   */
  data: Prisma.XOR<Prisma.ComandaCreateInput, Prisma.ComandaUncheckedCreateInput>
}

/**
 * Comanda createMany
 */
export type ComandaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Comandas.
   */
  data: Prisma.ComandaCreateManyInput | Prisma.ComandaCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Comanda createManyAndReturn
 */
export type ComandaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * The data used to create many Comandas.
   */
  data: Prisma.ComandaCreateManyInput | Prisma.ComandaCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Comanda update
 */
export type ComandaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * The data needed to update a Comanda.
   */
  data: Prisma.XOR<Prisma.ComandaUpdateInput, Prisma.ComandaUncheckedUpdateInput>
  /**
   * Choose, which Comanda to update.
   */
  where: Prisma.ComandaWhereUniqueInput
}

/**
 * Comanda updateMany
 */
export type ComandaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Comandas.
   */
  data: Prisma.XOR<Prisma.ComandaUpdateManyMutationInput, Prisma.ComandaUncheckedUpdateManyInput>
  /**
   * Filter which Comandas to update
   */
  where?: Prisma.ComandaWhereInput
  /**
   * Limit how many Comandas to update.
   */
  limit?: number
}

/**
 * Comanda updateManyAndReturn
 */
export type ComandaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * The data used to update Comandas.
   */
  data: Prisma.XOR<Prisma.ComandaUpdateManyMutationInput, Prisma.ComandaUncheckedUpdateManyInput>
  /**
   * Filter which Comandas to update
   */
  where?: Prisma.ComandaWhereInput
  /**
   * Limit how many Comandas to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Comanda upsert
 */
export type ComandaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * The filter to search for the Comanda to update in case it exists.
   */
  where: Prisma.ComandaWhereUniqueInput
  /**
   * In case the Comanda found by the `where` argument doesn't exist, create a new Comanda with this data.
   */
  create: Prisma.XOR<Prisma.ComandaCreateInput, Prisma.ComandaUncheckedCreateInput>
  /**
   * In case the Comanda was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ComandaUpdateInput, Prisma.ComandaUncheckedUpdateInput>
}

/**
 * Comanda delete
 */
export type ComandaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
  /**
   * Filter which Comanda to delete.
   */
  where: Prisma.ComandaWhereUniqueInput
}

/**
 * Comanda deleteMany
 */
export type ComandaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Comandas to delete
   */
  where?: Prisma.ComandaWhereInput
  /**
   * Limit how many Comandas to delete.
   */
  limit?: number
}

/**
 * Comanda.productos
 */
export type Comanda$productosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ComandaProductos
   */
  select?: Prisma.ComandaProductosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ComandaProductos
   */
  omit?: Prisma.ComandaProductosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaProductosInclude<ExtArgs> | null
  where?: Prisma.ComandaProductosWhereInput
  orderBy?: Prisma.ComandaProductosOrderByWithRelationInput | Prisma.ComandaProductosOrderByWithRelationInput[]
  cursor?: Prisma.ComandaProductosWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ComandaProductosScalarFieldEnum | Prisma.ComandaProductosScalarFieldEnum[]
}

/**
 * Comanda without action
 */
export type ComandaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Comanda
   */
  select?: Prisma.ComandaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Comanda
   */
  omit?: Prisma.ComandaOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ComandaInclude<ExtArgs> | null
}
