
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Empresas` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Empresas
 * 
 */
export type EmpresasModel = runtime.Types.Result.DefaultSelection<Prisma.$EmpresasPayload>

export type AggregateEmpresas = {
  _count: EmpresasCountAggregateOutputType | null
  _avg: EmpresasAvgAggregateOutputType | null
  _sum: EmpresasSumAggregateOutputType | null
  _min: EmpresasMinAggregateOutputType | null
  _max: EmpresasMaxAggregateOutputType | null
}

export type EmpresasAvgAggregateOutputType = {
  idEmpresa: number | null
}

export type EmpresasSumAggregateOutputType = {
  idEmpresa: number | null
}

export type EmpresasMinAggregateOutputType = {
  idEmpresa: number | null
  nombre: string | null
  email: string | null
  calle: string | null
  numero: string | null
  ciudad: string | null
  provincia: string | null
  codigoPostal: string | null
  pais: string | null
  contacto: string | null
  activo: boolean | null
}

export type EmpresasMaxAggregateOutputType = {
  idEmpresa: number | null
  nombre: string | null
  email: string | null
  calle: string | null
  numero: string | null
  ciudad: string | null
  provincia: string | null
  codigoPostal: string | null
  pais: string | null
  contacto: string | null
  activo: boolean | null
}

export type EmpresasCountAggregateOutputType = {
  idEmpresa: number
  nombre: number
  email: number
  calle: number
  numero: number
  ciudad: number
  provincia: number
  codigoPostal: number
  pais: number
  contacto: number
  activo: number
  _all: number
}


export type EmpresasAvgAggregateInputType = {
  idEmpresa?: true
}

export type EmpresasSumAggregateInputType = {
  idEmpresa?: true
}

export type EmpresasMinAggregateInputType = {
  idEmpresa?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
}

export type EmpresasMaxAggregateInputType = {
  idEmpresa?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
}

export type EmpresasCountAggregateInputType = {
  idEmpresa?: true
  nombre?: true
  email?: true
  calle?: true
  numero?: true
  ciudad?: true
  provincia?: true
  codigoPostal?: true
  pais?: true
  contacto?: true
  activo?: true
  _all?: true
}

export type EmpresasAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Empresas to aggregate.
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresasOrderByWithRelationInput | Prisma.EmpresasOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EmpresasWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Empresas
  **/
  _count?: true | EmpresasCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EmpresasAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EmpresasSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EmpresasMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EmpresasMaxAggregateInputType
}

export type GetEmpresasAggregateType<T extends EmpresasAggregateArgs> = {
      [P in keyof T & keyof AggregateEmpresas]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEmpresas[P]>
    : Prisma.GetScalarType<T[P], AggregateEmpresas[P]>
}




export type EmpresasGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EmpresasWhereInput
  orderBy?: Prisma.EmpresasOrderByWithAggregationInput | Prisma.EmpresasOrderByWithAggregationInput[]
  by: Prisma.EmpresasScalarFieldEnum[] | Prisma.EmpresasScalarFieldEnum
  having?: Prisma.EmpresasScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EmpresasCountAggregateInputType | true
  _avg?: EmpresasAvgAggregateInputType
  _sum?: EmpresasSumAggregateInputType
  _min?: EmpresasMinAggregateInputType
  _max?: EmpresasMaxAggregateInputType
}

export type EmpresasGroupByOutputType = {
  idEmpresa: number
  nombre: string
  email: string | null
  calle: string
  numero: string | null
  ciudad: string
  provincia: string
  codigoPostal: string
  pais: string
  contacto: string | null
  activo: boolean
  _count: EmpresasCountAggregateOutputType | null
  _avg: EmpresasAvgAggregateOutputType | null
  _sum: EmpresasSumAggregateOutputType | null
  _min: EmpresasMinAggregateOutputType | null
  _max: EmpresasMaxAggregateOutputType | null
}

type GetEmpresasGroupByPayload<T extends EmpresasGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EmpresasGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EmpresasGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EmpresasGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EmpresasGroupByOutputType[P]>
      }
    >
  >



export type EmpresasWhereInput = {
  AND?: Prisma.EmpresasWhereInput | Prisma.EmpresasWhereInput[]
  OR?: Prisma.EmpresasWhereInput[]
  NOT?: Prisma.EmpresasWhereInput | Prisma.EmpresasWhereInput[]
  idEmpresa?: Prisma.IntFilter<"Empresas"> | number
  nombre?: Prisma.StringFilter<"Empresas"> | string
  email?: Prisma.StringNullableFilter<"Empresas"> | string | null
  calle?: Prisma.StringFilter<"Empresas"> | string
  numero?: Prisma.StringNullableFilter<"Empresas"> | string | null
  ciudad?: Prisma.StringFilter<"Empresas"> | string
  provincia?: Prisma.StringFilter<"Empresas"> | string
  codigoPostal?: Prisma.StringFilter<"Empresas"> | string
  pais?: Prisma.StringFilter<"Empresas"> | string
  contacto?: Prisma.StringNullableFilter<"Empresas"> | string | null
  activo?: Prisma.BoolFilter<"Empresas"> | boolean
}

export type EmpresasOrderByWithRelationInput = {
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrderInput | Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrderInput | Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type EmpresasWhereUniqueInput = Prisma.AtLeast<{
  idEmpresa?: number
  AND?: Prisma.EmpresasWhereInput | Prisma.EmpresasWhereInput[]
  OR?: Prisma.EmpresasWhereInput[]
  NOT?: Prisma.EmpresasWhereInput | Prisma.EmpresasWhereInput[]
  nombre?: Prisma.StringFilter<"Empresas"> | string
  email?: Prisma.StringNullableFilter<"Empresas"> | string | null
  calle?: Prisma.StringFilter<"Empresas"> | string
  numero?: Prisma.StringNullableFilter<"Empresas"> | string | null
  ciudad?: Prisma.StringFilter<"Empresas"> | string
  provincia?: Prisma.StringFilter<"Empresas"> | string
  codigoPostal?: Prisma.StringFilter<"Empresas"> | string
  pais?: Prisma.StringFilter<"Empresas"> | string
  contacto?: Prisma.StringNullableFilter<"Empresas"> | string | null
  activo?: Prisma.BoolFilter<"Empresas"> | boolean
}, "idEmpresa">

export type EmpresasOrderByWithAggregationInput = {
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrderInput | Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrderInput | Prisma.SortOrder
  activo?: Prisma.SortOrder
  _count?: Prisma.EmpresasCountOrderByAggregateInput
  _avg?: Prisma.EmpresasAvgOrderByAggregateInput
  _max?: Prisma.EmpresasMaxOrderByAggregateInput
  _min?: Prisma.EmpresasMinOrderByAggregateInput
  _sum?: Prisma.EmpresasSumOrderByAggregateInput
}

export type EmpresasScalarWhereWithAggregatesInput = {
  AND?: Prisma.EmpresasScalarWhereWithAggregatesInput | Prisma.EmpresasScalarWhereWithAggregatesInput[]
  OR?: Prisma.EmpresasScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EmpresasScalarWhereWithAggregatesInput | Prisma.EmpresasScalarWhereWithAggregatesInput[]
  idEmpresa?: Prisma.IntWithAggregatesFilter<"Empresas"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"Empresas"> | string | null
  calle?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  numero?: Prisma.StringNullableWithAggregatesFilter<"Empresas"> | string | null
  ciudad?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  provincia?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  codigoPostal?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  pais?: Prisma.StringWithAggregatesFilter<"Empresas"> | string
  contacto?: Prisma.StringNullableWithAggregatesFilter<"Empresas"> | string | null
  activo?: Prisma.BoolWithAggregatesFilter<"Empresas"> | boolean
}

export type EmpresasCreateInput = {
  idEmpresa?: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
}

export type EmpresasUncheckedCreateInput = {
  idEmpresa?: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
}

export type EmpresasUpdateInput = {
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EmpresasUncheckedUpdateInput = {
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EmpresasCreateManyInput = {
  idEmpresa?: number
  nombre: string
  email?: string | null
  calle?: string
  numero?: string | null
  ciudad?: string
  provincia?: string
  codigoPostal?: string
  pais?: string
  contacto?: string | null
  activo?: boolean
}

export type EmpresasUpdateManyMutationInput = {
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EmpresasUncheckedUpdateManyInput = {
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  calle?: Prisma.StringFieldUpdateOperationsInput | string
  numero?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ciudad?: Prisma.StringFieldUpdateOperationsInput | string
  provincia?: Prisma.StringFieldUpdateOperationsInput | string
  codigoPostal?: Prisma.StringFieldUpdateOperationsInput | string
  pais?: Prisma.StringFieldUpdateOperationsInput | string
  contacto?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type EmpresasCountOrderByAggregateInput = {
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type EmpresasAvgOrderByAggregateInput = {
  idEmpresa?: Prisma.SortOrder
}

export type EmpresasMaxOrderByAggregateInput = {
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type EmpresasMinOrderByAggregateInput = {
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  email?: Prisma.SortOrder
  calle?: Prisma.SortOrder
  numero?: Prisma.SortOrder
  ciudad?: Prisma.SortOrder
  provincia?: Prisma.SortOrder
  codigoPostal?: Prisma.SortOrder
  pais?: Prisma.SortOrder
  contacto?: Prisma.SortOrder
  activo?: Prisma.SortOrder
}

export type EmpresasSumOrderByAggregateInput = {
  idEmpresa?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}



export type EmpresasSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idEmpresa?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
}, ExtArgs["result"]["empresas"]>

export type EmpresasSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idEmpresa?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
}, ExtArgs["result"]["empresas"]>

export type EmpresasSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idEmpresa?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
}, ExtArgs["result"]["empresas"]>

export type EmpresasSelectScalar = {
  idEmpresa?: boolean
  nombre?: boolean
  email?: boolean
  calle?: boolean
  numero?: boolean
  ciudad?: boolean
  provincia?: boolean
  codigoPostal?: boolean
  pais?: boolean
  contacto?: boolean
  activo?: boolean
}

export type EmpresasOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idEmpresa" | "nombre" | "email" | "calle" | "numero" | "ciudad" | "provincia" | "codigoPostal" | "pais" | "contacto" | "activo", ExtArgs["result"]["empresas"]>

export type $EmpresasPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Empresas"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idEmpresa: number
    nombre: string
    email: string | null
    calle: string
    numero: string | null
    ciudad: string
    provincia: string
    codigoPostal: string
    pais: string
    contacto: string | null
    activo: boolean
  }, ExtArgs["result"]["empresas"]>
  composites: {}
}

export type EmpresasGetPayload<S extends boolean | null | undefined | EmpresasDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EmpresasPayload, S>

export type EmpresasCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EmpresasFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EmpresasCountAggregateInputType | true
  }

export interface EmpresasDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Empresas'], meta: { name: 'Empresas' } }
  /**
   * Find zero or one Empresas that matches the filter.
   * @param {EmpresasFindUniqueArgs} args - Arguments to find a Empresas
   * @example
   * // Get one Empresas
   * const empresas = await prisma.empresas.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EmpresasFindUniqueArgs>(args: Prisma.SelectSubset<T, EmpresasFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Empresas that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EmpresasFindUniqueOrThrowArgs} args - Arguments to find a Empresas
   * @example
   * // Get one Empresas
   * const empresas = await prisma.empresas.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EmpresasFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EmpresasFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasFindFirstArgs} args - Arguments to find a Empresas
   * @example
   * // Get one Empresas
   * const empresas = await prisma.empresas.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EmpresasFindFirstArgs>(args?: Prisma.SelectSubset<T, EmpresasFindFirstArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Empresas that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasFindFirstOrThrowArgs} args - Arguments to find a Empresas
   * @example
   * // Get one Empresas
   * const empresas = await prisma.empresas.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EmpresasFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EmpresasFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Empresas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Empresas
   * const empresas = await prisma.empresas.findMany()
   * 
   * // Get first 10 Empresas
   * const empresas = await prisma.empresas.findMany({ take: 10 })
   * 
   * // Only select the `idEmpresa`
   * const empresasWithIdEmpresaOnly = await prisma.empresas.findMany({ select: { idEmpresa: true } })
   * 
   */
  findMany<T extends EmpresasFindManyArgs>(args?: Prisma.SelectSubset<T, EmpresasFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Empresas.
   * @param {EmpresasCreateArgs} args - Arguments to create a Empresas.
   * @example
   * // Create one Empresas
   * const Empresas = await prisma.empresas.create({
   *   data: {
   *     // ... data to create a Empresas
   *   }
   * })
   * 
   */
  create<T extends EmpresasCreateArgs>(args: Prisma.SelectSubset<T, EmpresasCreateArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Empresas.
   * @param {EmpresasCreateManyArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresas = await prisma.empresas.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EmpresasCreateManyArgs>(args?: Prisma.SelectSubset<T, EmpresasCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Empresas and returns the data saved in the database.
   * @param {EmpresasCreateManyAndReturnArgs} args - Arguments to create many Empresas.
   * @example
   * // Create many Empresas
   * const empresas = await prisma.empresas.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Empresas and only return the `idEmpresa`
   * const empresasWithIdEmpresaOnly = await prisma.empresas.createManyAndReturn({
   *   select: { idEmpresa: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EmpresasCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EmpresasCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Empresas.
   * @param {EmpresasDeleteArgs} args - Arguments to delete one Empresas.
   * @example
   * // Delete one Empresas
   * const Empresas = await prisma.empresas.delete({
   *   where: {
   *     // ... filter to delete one Empresas
   *   }
   * })
   * 
   */
  delete<T extends EmpresasDeleteArgs>(args: Prisma.SelectSubset<T, EmpresasDeleteArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Empresas.
   * @param {EmpresasUpdateArgs} args - Arguments to update one Empresas.
   * @example
   * // Update one Empresas
   * const empresas = await prisma.empresas.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EmpresasUpdateArgs>(args: Prisma.SelectSubset<T, EmpresasUpdateArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Empresas.
   * @param {EmpresasDeleteManyArgs} args - Arguments to filter Empresas to delete.
   * @example
   * // Delete a few Empresas
   * const { count } = await prisma.empresas.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EmpresasDeleteManyArgs>(args?: Prisma.SelectSubset<T, EmpresasDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Empresas
   * const empresas = await prisma.empresas.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EmpresasUpdateManyArgs>(args: Prisma.SelectSubset<T, EmpresasUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Empresas and returns the data updated in the database.
   * @param {EmpresasUpdateManyAndReturnArgs} args - Arguments to update many Empresas.
   * @example
   * // Update many Empresas
   * const empresas = await prisma.empresas.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Empresas and only return the `idEmpresa`
   * const empresasWithIdEmpresaOnly = await prisma.empresas.updateManyAndReturn({
   *   select: { idEmpresa: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EmpresasUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EmpresasUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Empresas.
   * @param {EmpresasUpsertArgs} args - Arguments to update or create a Empresas.
   * @example
   * // Update or create a Empresas
   * const empresas = await prisma.empresas.upsert({
   *   create: {
   *     // ... data to create a Empresas
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Empresas we want to update
   *   }
   * })
   */
  upsert<T extends EmpresasUpsertArgs>(args: Prisma.SelectSubset<T, EmpresasUpsertArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasCountArgs} args - Arguments to filter Empresas to count.
   * @example
   * // Count the number of Empresas
   * const count = await prisma.empresas.count({
   *   where: {
   *     // ... the filter for the Empresas we want to count
   *   }
   * })
  **/
  count<T extends EmpresasCountArgs>(
    args?: Prisma.Subset<T, EmpresasCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EmpresasCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EmpresasAggregateArgs>(args: Prisma.Subset<T, EmpresasAggregateArgs>): Prisma.PrismaPromise<GetEmpresasAggregateType<T>>

  /**
   * Group by Empresas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EmpresasGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EmpresasGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EmpresasGroupByArgs['orderBy'] }
      : { orderBy?: EmpresasGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EmpresasGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEmpresasGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Empresas model
 */
readonly fields: EmpresasFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Empresas.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EmpresasClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Empresas model
 */
export interface EmpresasFieldRefs {
  readonly idEmpresa: Prisma.FieldRef<"Empresas", 'Int'>
  readonly nombre: Prisma.FieldRef<"Empresas", 'String'>
  readonly email: Prisma.FieldRef<"Empresas", 'String'>
  readonly calle: Prisma.FieldRef<"Empresas", 'String'>
  readonly numero: Prisma.FieldRef<"Empresas", 'String'>
  readonly ciudad: Prisma.FieldRef<"Empresas", 'String'>
  readonly provincia: Prisma.FieldRef<"Empresas", 'String'>
  readonly codigoPostal: Prisma.FieldRef<"Empresas", 'String'>
  readonly pais: Prisma.FieldRef<"Empresas", 'String'>
  readonly contacto: Prisma.FieldRef<"Empresas", 'String'>
  readonly activo: Prisma.FieldRef<"Empresas", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Empresas findUnique
 */
export type EmpresasFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where: Prisma.EmpresasWhereUniqueInput
}

/**
 * Empresas findUniqueOrThrow
 */
export type EmpresasFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where: Prisma.EmpresasWhereUniqueInput
}

/**
 * Empresas findFirst
 */
export type EmpresasFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresasOrderByWithRelationInput | Prisma.EmpresasOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Empresas.
   */
  cursor?: Prisma.EmpresasWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Empresas.
   */
  distinct?: Prisma.EmpresasScalarFieldEnum | Prisma.EmpresasScalarFieldEnum[]
}

/**
 * Empresas findFirstOrThrow
 */
export type EmpresasFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresasOrderByWithRelationInput | Prisma.EmpresasOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Empresas.
   */
  cursor?: Prisma.EmpresasWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Empresas.
   */
  distinct?: Prisma.EmpresasScalarFieldEnum | Prisma.EmpresasScalarFieldEnum[]
}

/**
 * Empresas findMany
 */
export type EmpresasFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter, which Empresas to fetch.
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Empresas to fetch.
   */
  orderBy?: Prisma.EmpresasOrderByWithRelationInput | Prisma.EmpresasOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Empresas.
   */
  cursor?: Prisma.EmpresasWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Empresas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Empresas.
   */
  skip?: number
  distinct?: Prisma.EmpresasScalarFieldEnum | Prisma.EmpresasScalarFieldEnum[]
}

/**
 * Empresas create
 */
export type EmpresasCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * The data needed to create a Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresasCreateInput, Prisma.EmpresasUncheckedCreateInput>
}

/**
 * Empresas createMany
 */
export type EmpresasCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Empresas.
   */
  data: Prisma.EmpresasCreateManyInput | Prisma.EmpresasCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Empresas createManyAndReturn
 */
export type EmpresasCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * The data used to create many Empresas.
   */
  data: Prisma.EmpresasCreateManyInput | Prisma.EmpresasCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Empresas update
 */
export type EmpresasUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * The data needed to update a Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresasUpdateInput, Prisma.EmpresasUncheckedUpdateInput>
  /**
   * Choose, which Empresas to update.
   */
  where: Prisma.EmpresasWhereUniqueInput
}

/**
 * Empresas updateMany
 */
export type EmpresasUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresasUpdateManyMutationInput, Prisma.EmpresasUncheckedUpdateManyInput>
  /**
   * Filter which Empresas to update
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * Limit how many Empresas to update.
   */
  limit?: number
}

/**
 * Empresas updateManyAndReturn
 */
export type EmpresasUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * The data used to update Empresas.
   */
  data: Prisma.XOR<Prisma.EmpresasUpdateManyMutationInput, Prisma.EmpresasUncheckedUpdateManyInput>
  /**
   * Filter which Empresas to update
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * Limit how many Empresas to update.
   */
  limit?: number
}

/**
 * Empresas upsert
 */
export type EmpresasUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * The filter to search for the Empresas to update in case it exists.
   */
  where: Prisma.EmpresasWhereUniqueInput
  /**
   * In case the Empresas found by the `where` argument doesn't exist, create a new Empresas with this data.
   */
  create: Prisma.XOR<Prisma.EmpresasCreateInput, Prisma.EmpresasUncheckedCreateInput>
  /**
   * In case the Empresas was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EmpresasUpdateInput, Prisma.EmpresasUncheckedUpdateInput>
}

/**
 * Empresas delete
 */
export type EmpresasDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
  /**
   * Filter which Empresas to delete.
   */
  where: Prisma.EmpresasWhereUniqueInput
}

/**
 * Empresas deleteMany
 */
export type EmpresasDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Empresas to delete
   */
  where?: Prisma.EmpresasWhereInput
  /**
   * Limit how many Empresas to delete.
   */
  limit?: number
}

/**
 * Empresas without action
 */
export type EmpresasDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Empresas
   */
  select?: Prisma.EmpresasSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Empresas
   */
  omit?: Prisma.EmpresasOmit<ExtArgs> | null
}
