openapi: 3.0.3
info:
  title: Perfil API
  description: API para gestión de perfiles de usuario y cliente. Soporta acceso personal vía JWT y acceso administrativo vía ID.
  version: "1.1.0"
servers:
  - url: http://localhost:3000/api
    description: Servidor Local
  - url: https://api.empresa.com/v1
    description: Producción

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      
  schemas:
    Rol:
      type: string
      enum: [USER, ADMIN, SUPER]
      default: USER
    
    Usuario:
      type: object
      required: [idUsuario, username, email, nombre, rol]
      properties:
        idUsuario: { type: integer, example: 1 }
        username: { type: string, example: "juanperez" }
        email: { type: string, format: email, example: "juan@email.com" }
        nombre: { type: string, example: "Juan Pérez" }
        activo: { type: boolean, example: true }
        rol: { $ref: "#/components/schemas/Rol" }
        creadoEn: { type: string, format: date-time }
        actualizadoEn: { type: string, format: date-time }

    Cliente:
      type: object
      properties:
        idCliente: { type: integer, example: 10 }
        calle: { type: string, example: "Calle Falsa 123" }
        ciudad: { type: string, example: "Madrid" }
        provincia: { type: string, example: "Madrid" }
        pais: { type: string, example: "España" }
        contacto: { type: string, example: "+34 600 000 000" }

    PerfilCompleto:
      allOf:
        - $ref: "#/components/schemas/Usuario"
        - type: object
          properties:
            cliente:
              $ref: "#/components/schemas/Cliente"
              nullable: true

    UpdatePerfilRequest:
      type: object
      properties:
        nombre: { type: string, minLength: 2 }
        email: { type: string, format: email }
        cliente:
          type: object
          properties:
            calle: { type: string }
            ciudad: { type: string }
            provincia: { type: string }
            contacto: { type: string }

    # Estandarización de respuestas según tu controlador Koa
    GenericResponse:
      type: object
      properties:
        success: { type: boolean }
        message: { type: string }

    ProfileSuccessResponse:
      allOf:
        - $ref: "#/components/schemas/GenericResponse"
        - type: object
          properties:
            perfil: { $ref: "#/components/schemas/PerfilCompleto" }

    ValidationErrorResponse:
      allOf:
        - $ref: "#/components/schemas/GenericResponse"
        - type: object
          properties:
            errors:
              type: array
              items:
                type: object
                properties:
                  field: { type: string }
                  message: { type: string }

paths:
  # RUTA PERSONAL (Usa el ID del JWT)
  /perfil:
    get:
      tags: [Perfil]
      summary: Obtiene mi propio perfil
      security: [{ bearerAuth: [] }]
      responses:
        "200":
          description: Perfil devuelto exitosamente
          content:
            application/json:
              schema: { $ref: "#/components/schemas/PerfilCompleto" }
        "401":
          $ref: "#/components/responses/Unauthorized"

    put:
      tags: [Perfil]
      summary: Actualiza mi propio perfil
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UpdatePerfilRequest" }
      responses:
        "200":
          description: Perfil actualizado
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ProfileSuccessResponse" }
        "400":
          description: Error de validación (Zod)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ValidationErrorResponse" }
        "409":
          description: Conflicto (Email en uso)
          content:
            application/json:
              schema: { $ref: "#/components/schemas/GenericResponse" }

  # RUTA ADMINISTRATIVA (Usa el ID de la URL)
  /perfil/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: integer }
    get:
      tags: [Admin]
      summary: Obtiene perfil de cualquier usuario (Admin)
      security: [{ bearerAuth: [] }]
      responses:
        "200":
          content:
            application/json:
              schema: { $ref: "#/components/schemas/PerfilCompleto" }
        "403":
          description: No tienes permisos de Admin
    put:
      tags: [Admin]
      summary: Actualiza perfil de cualquier usuario (Admin)
      security: [{ bearerAuth: [] }]
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/UpdatePerfilRequest" }
      responses:
        "200":
          content:
            application/json:
              schema: { $ref: "#/components/schemas/ProfileSuccessResponse" }

responses:
  Unauthorized:
    description: No autorizado
    content:
      application/json:
        schema: { $ref: "#/components/schemas/GenericResponse" }
        example: { success: false, message: "Token inválido o expirado" }