openapi: 3.0.3
info:
  title: Docs API
  version: "1.0.0"
servers:
  - url: http://localhost:{PORT}
    variables:
      PORT:
        default: "3000"

paths:
  /docs/specs:
    get:
      tags: [Public]
      summary: Lista todos los specs disponibles
      responses:
        "200":
          description: Lista de módulos/specs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /docs/specs/{module}/{file}:
    get:
      tags: [Public]
      summary: Obtiene el YAML de un spec específico
      parameters:
        - in: path
          name: module
          required: true
          schema:
            type: string
        - in: path
          name: file
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Contenido YAML del spec
          content:
            application/x-yaml:
              schema:
                type: string
        "404":
          description: Spec no encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
