openapi: 3.0.3
info:
  title: Clientes API
  version: "1.0.0"

servers:
  - url: http://localhost:{PORT}
    variables:
      PORT:
        default: "3000"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Cliente:
      type: object
      required:
        - idCliente
        - nombre
        - activo
      properties:
        idCliente:
          type: integer
        idUsuario:
          type: integer
        nombre:
          type: string
        email:
          type: string
          nullable: true
        calle:
          type: string
        numero:
          type: string
          nullable: true
        ciudad:
          type: string
        provincia:
          type: string
        codigoPostal:
          type: string
        pais:
          type: string
        contacto:
          type: string
          nullable: true
        activo:
          type: boolean
        usuario:
          type: object
          additionalProperties: true
        historial:
          type: array
          items:
            type: object
            additionalProperties: true

paths:
  /api/clientes:
    get:
      tags: [Dashboard]
      summary: Lista clientes (ADMIN)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cliente"
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    post:
      tags: [Dashboard]
      summary: Crea un cliente a partir de un usuario existente (ADMIN)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - idUsuario
                - nombre
              properties:
                idUsuario:
                  type: integer
                  minimum: 1
                nombre:
                  type: string
                  minLength: 2
                calle:
                  type: string
                numero:
                  type: string
                ciudad:
                  type: string
                provincia:
                  type: string
                codigoPostal:
                  type: string
                pais:
                  type: string
                contacto:
                  type: string
                activo:
                  type: boolean
      responses:
        "200":
          description: Creado (la implementación devuelve 200)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "400":
          description: Body inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

  /api/clientes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer

    get:
      tags: [Dashboard]
      summary: Obtiene un cliente por id (ADMIN)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    patch:
      tags: [Dashboard]
      summary: Actualiza un cliente (ADMIN)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idUsuario:
                  type: integer
                nombre:
                  type: string
                calle:
                  type: string
                numero:
                  type: string
                ciudad:
                  type: string
                provincia:
                  type: string
                codigoPostal:
                  type: string
                pais:
                  type: string
                contacto:
                  type: string
                activo:
                  type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "400":
          description: Body inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

    delete:
      tags: [Dashboard]
      summary: Desactiva (soft delete) el cliente (ADMIN)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cliente"
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  message:
                    type: string
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
