openapi: 3.0.3
info:
  title: Categorías API
  version: "1.0.0"
servers:
  - url: http://localhost:{PORT}
    variables:
      PORT:
        default: "3000"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Categoria:
      type: object
      properties:
        idCategoria: { type: integer }
        nombre: { type: string }
        descripcion: { type: string, nullable: true }
        icono: { type: string, nullable: true }
        tipo:
          type: string
          enum: [FAMILIA, MADRE, HIJA]
        activo: { type: boolean }
        idCategoriaPadre: { type: integer, nullable: true }
        subcategorias:
          type: array
          items:
            $ref: "#/components/schemas/Categoria"
paths:
  /categorias/:
    get:
      tags: [Categorías]
      summary: Devuelve el árbol familias → madres → hijas (solo activo=true)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  familias:
                    type: array
                    items:
                      $ref: "#/components/schemas/Categoria"
  /categorias/{id}:
    get:
      tags: [Categorías]
      summary: Detalle de categoría por id (incluye subcategorias activas)
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        "400":
          description: Id inválido o categoría no existe
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
  /categorias/madres:
    get:
      tags: [Categorías]
      summary: Lista categorías tipo MADRE
      parameters:
        - in: query
          name: idFamilia
          required: false
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  madres:
                    type: array
                    items:
                      $ref: "#/components/schemas/Categoria"
  /categorias/hijas:
    get:
      tags: [Categorías]
      summary: Lista categorías tipo HIJA
      parameters:
        - in: query
          name: idMadre
          required: false
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  hijas:
                    type: array
                    items:
                      $ref: "#/components/schemas/Categoria"
  /api/dashboard/categorias:
    post:
      tags: [Categorías, Dashboard]
      summary: Crea una categoría (ADMIN)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [nombre, tipo]
              properties:
                nombre: { type: string, minLength: 1 }
                descripcion: { type: string }
                icono: { type: string }
                tipo:
                  type: string
                  enum: [FAMILIA, MADRE, HIJA]
                idCategoriaPadre: { type: integer, nullable: true }
      responses:
        "201":
          description: Creada
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        "400":
          description: Validación / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
  /api/dashboard/categorias/{id}:
    patch:
      tags: [Categorías, Dashboard]
      summary: Actualiza una categoría (ADMIN)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre: { type: string, minLength: 1 }
                descripcion: { type: string }
                icono: { type: string }
                activo: { type: boolean }
                idCategoriaPadre: { type: integer, nullable: true }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"
        "400":
          description: Validación / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
  /api/dashboard/categorias/{id}/desactivar:
    patch:
      tags: [Categorías, Dashboard]
      summary: Desactiva una categoría (ADMIN)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        "400":
          description: Regla de negocio / validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
    delete:
      tags: [Categorías, Dashboard]
      summary: Elimina físicamente una categoría (ADMIN)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
        "400":
          description: Regla de negocio / validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
