openapi: 3.0.3
info:
  title: Producto Componentes (BOM) API
  version: "1.0.0"
servers:
  - url: http://localhost:{PORT}
    variables:
      PORT:
        default: "3000"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ProductoComponente:
      type: object
      properties:
        id: { type: integer }
        idProductoPadre: { type: integer }
        idProductoComponente: { type: integer }
        cantidad: { type: number }
        productoComponente:
          type: object
          additionalProperties: true
paths:
  /api/dashboard/componentes:
    post:
      tags: [Componentes, Dashboard]
      summary: Agrega un componente a un producto padre (ADMIN)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [idProductoPadre, idProductoComponente, cantidad]
              properties:
                idProductoPadre: { type: integer, minimum: 1 }
                idProductoComponente: { type: integer, minimum: 1 }
                cantidad: { type: number, exclusiveMinimum: 0 }
      responses:
        "201":
          description: Creado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductoComponente"
        "400":
          description: Body inválido / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
                  message: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
  /api/dashboard/componentes/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema: { type: integer }
    get:
      tags: [Componentes, Dashboard]
      summary: Obtiene un componente por id (ADMIN)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductoComponente"
        "400":
          description: Body inválido / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
                  message: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
    put:
      tags: [Componentes, Dashboard]
      summary: Actualiza un componente (ADMIN)
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idProductoPadre: { type: integer, minimum: 1 }
                idProductoComponente: { type: integer, minimum: 1 }
                cantidad: { type: number, exclusiveMinimum: 0 }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProductoComponente"
        "400":
          description: Body inválido / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
                  message: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
    delete:
      tags: [Componentes, Dashboard]
      summary: Elimina físicamente el componente (ADMIN)
      security:
        - bearerAuth: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: integer }
        "400":
          description: Body inválido / regla de negocio
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
                  message: { type: string }
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
  /api/dashboard/componentes/padre/{idProductoPadre}:
    get:
      tags: [Componentes, Dashboard]
      summary: Lista componentes por producto padre (ADMIN)
      security:
        - bearerAuth: []
      parameters:
        - in: path
          name: idProductoPadre
          required: true
          schema: { type: integer }
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductoComponente"
        "401":
          description: Sin token / token inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
                  error: { type: string }
        "403":
          description: No admin
          content:
            application/json:
              schema:
                type: object
                properties:
                  error: { type: string }
