import type { Prisma } from '../client';
import * as z from 'zod';
import { UsuarioEmpresaOrderByWithRelationInputObjectSchema as UsuarioEmpresaOrderByWithRelationInputObjectSchema } from './objects/UsuarioEmpresaOrderByWithRelationInput.schema';
import { UsuarioEmpresaWhereInputObjectSchema as UsuarioEmpresaWhereInputObjectSchema } from './objects/UsuarioEmpresaWhereInput.schema';
import { UsuarioEmpresaWhereUniqueInputObjectSchema as UsuarioEmpresaWhereUniqueInputObjectSchema } from './objects/UsuarioEmpresaWhereUniqueInput.schema';
import { UsuarioEmpresaCountAggregateInputObjectSchema as UsuarioEmpresaCountAggregateInputObjectSchema } from './objects/UsuarioEmpresaCountAggregateInput.schema';
import { UsuarioEmpresaMinAggregateInputObjectSchema as UsuarioEmpresaMinAggregateInputObjectSchema } from './objects/UsuarioEmpresaMinAggregateInput.schema';
import { UsuarioEmpresaMaxAggregateInputObjectSchema as UsuarioEmpresaMaxAggregateInputObjectSchema } from './objects/UsuarioEmpresaMaxAggregateInput.schema';
import { UsuarioEmpresaAvgAggregateInputObjectSchema as UsuarioEmpresaAvgAggregateInputObjectSchema } from './objects/UsuarioEmpresaAvgAggregateInput.schema';
import { UsuarioEmpresaSumAggregateInputObjectSchema as UsuarioEmpresaSumAggregateInputObjectSchema } from './objects/UsuarioEmpresaSumAggregateInput.schema';

export const UsuarioEmpresaAggregateSchema: z.ZodType<Prisma.UsuarioEmpresaAggregateArgs> = z.object({ orderBy: z.union([UsuarioEmpresaOrderByWithRelationInputObjectSchema, UsuarioEmpresaOrderByWithRelationInputObjectSchema.array()]).optional(), where: UsuarioEmpresaWhereInputObjectSchema.optional(), cursor: UsuarioEmpresaWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), UsuarioEmpresaCountAggregateInputObjectSchema ]).optional(), _min: UsuarioEmpresaMinAggregateInputObjectSchema.optional(), _max: UsuarioEmpresaMaxAggregateInputObjectSchema.optional(), _avg: UsuarioEmpresaAvgAggregateInputObjectSchema.optional(), _sum: UsuarioEmpresaSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.UsuarioEmpresaAggregateArgs>;

export const UsuarioEmpresaAggregateZodSchema = z.object({ orderBy: z.union([UsuarioEmpresaOrderByWithRelationInputObjectSchema, UsuarioEmpresaOrderByWithRelationInputObjectSchema.array()]).optional(), where: UsuarioEmpresaWhereInputObjectSchema.optional(), cursor: UsuarioEmpresaWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), UsuarioEmpresaCountAggregateInputObjectSchema ]).optional(), _min: UsuarioEmpresaMinAggregateInputObjectSchema.optional(), _max: UsuarioEmpresaMaxAggregateInputObjectSchema.optional(), _avg: UsuarioEmpresaAvgAggregateInputObjectSchema.optional(), _sum: UsuarioEmpresaSumAggregateInputObjectSchema.optional() }).strict();