import type { Prisma } from '../client';
import * as z from 'zod';
import { ListaPvpOrderByWithRelationInputObjectSchema as ListaPvpOrderByWithRelationInputObjectSchema } from './objects/ListaPvpOrderByWithRelationInput.schema';
import { ListaPvpWhereInputObjectSchema as ListaPvpWhereInputObjectSchema } from './objects/ListaPvpWhereInput.schema';
import { ListaPvpWhereUniqueInputObjectSchema as ListaPvpWhereUniqueInputObjectSchema } from './objects/ListaPvpWhereUniqueInput.schema';
import { ListaPvpCountAggregateInputObjectSchema as ListaPvpCountAggregateInputObjectSchema } from './objects/ListaPvpCountAggregateInput.schema';
import { ListaPvpMinAggregateInputObjectSchema as ListaPvpMinAggregateInputObjectSchema } from './objects/ListaPvpMinAggregateInput.schema';
import { ListaPvpMaxAggregateInputObjectSchema as ListaPvpMaxAggregateInputObjectSchema } from './objects/ListaPvpMaxAggregateInput.schema';
import { ListaPvpAvgAggregateInputObjectSchema as ListaPvpAvgAggregateInputObjectSchema } from './objects/ListaPvpAvgAggregateInput.schema';
import { ListaPvpSumAggregateInputObjectSchema as ListaPvpSumAggregateInputObjectSchema } from './objects/ListaPvpSumAggregateInput.schema';

export const ListaPvpAggregateSchema: z.ZodType<Prisma.ListaPvpAggregateArgs> = z.object({ orderBy: z.union([ListaPvpOrderByWithRelationInputObjectSchema, ListaPvpOrderByWithRelationInputObjectSchema.array()]).optional(), where: ListaPvpWhereInputObjectSchema.optional(), cursor: ListaPvpWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ListaPvpCountAggregateInputObjectSchema ]).optional(), _min: ListaPvpMinAggregateInputObjectSchema.optional(), _max: ListaPvpMaxAggregateInputObjectSchema.optional(), _avg: ListaPvpAvgAggregateInputObjectSchema.optional(), _sum: ListaPvpSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.ListaPvpAggregateArgs>;

export const ListaPvpAggregateZodSchema = z.object({ orderBy: z.union([ListaPvpOrderByWithRelationInputObjectSchema, ListaPvpOrderByWithRelationInputObjectSchema.array()]).optional(), where: ListaPvpWhereInputObjectSchema.optional(), cursor: ListaPvpWhereUniqueInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), _count: z.union([ z.literal(true), ListaPvpCountAggregateInputObjectSchema ]).optional(), _min: ListaPvpMinAggregateInputObjectSchema.optional(), _max: ListaPvpMaxAggregateInputObjectSchema.optional(), _avg: ListaPvpAvgAggregateInputObjectSchema.optional(), _sum: ListaPvpSumAggregateInputObjectSchema.optional() }).strict();