import type { Prisma } from '../client';
import * as z from 'zod';
import { UsuarioEmpresaWhereInputObjectSchema as UsuarioEmpresaWhereInputObjectSchema } from './objects/UsuarioEmpresaWhereInput.schema';
import { UsuarioEmpresaOrderByWithAggregationInputObjectSchema as UsuarioEmpresaOrderByWithAggregationInputObjectSchema } from './objects/UsuarioEmpresaOrderByWithAggregationInput.schema';
import { UsuarioEmpresaScalarWhereWithAggregatesInputObjectSchema as UsuarioEmpresaScalarWhereWithAggregatesInputObjectSchema } from './objects/UsuarioEmpresaScalarWhereWithAggregatesInput.schema';
import { UsuarioEmpresaScalarFieldEnumSchema } from './enums/UsuarioEmpresaScalarFieldEnum.schema';
import { UsuarioEmpresaCountAggregateInputObjectSchema as UsuarioEmpresaCountAggregateInputObjectSchema } from './objects/UsuarioEmpresaCountAggregateInput.schema';
import { UsuarioEmpresaMinAggregateInputObjectSchema as UsuarioEmpresaMinAggregateInputObjectSchema } from './objects/UsuarioEmpresaMinAggregateInput.schema';
import { UsuarioEmpresaMaxAggregateInputObjectSchema as UsuarioEmpresaMaxAggregateInputObjectSchema } from './objects/UsuarioEmpresaMaxAggregateInput.schema';
import { UsuarioEmpresaAvgAggregateInputObjectSchema as UsuarioEmpresaAvgAggregateInputObjectSchema } from './objects/UsuarioEmpresaAvgAggregateInput.schema';
import { UsuarioEmpresaSumAggregateInputObjectSchema as UsuarioEmpresaSumAggregateInputObjectSchema } from './objects/UsuarioEmpresaSumAggregateInput.schema';

export const UsuarioEmpresaGroupBySchema: z.ZodType<Prisma.UsuarioEmpresaGroupByArgs> = z.object({ where: UsuarioEmpresaWhereInputObjectSchema.optional(), orderBy: z.union([UsuarioEmpresaOrderByWithAggregationInputObjectSchema, UsuarioEmpresaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: UsuarioEmpresaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(UsuarioEmpresaScalarFieldEnumSchema), _count: z.union([ z.literal(true), UsuarioEmpresaCountAggregateInputObjectSchema ]).optional(), _min: UsuarioEmpresaMinAggregateInputObjectSchema.optional(), _max: UsuarioEmpresaMaxAggregateInputObjectSchema.optional(), _avg: UsuarioEmpresaAvgAggregateInputObjectSchema.optional(), _sum: UsuarioEmpresaSumAggregateInputObjectSchema.optional() }).strict() as unknown as z.ZodType<Prisma.UsuarioEmpresaGroupByArgs>;

export const UsuarioEmpresaGroupByZodSchema = z.object({ where: UsuarioEmpresaWhereInputObjectSchema.optional(), orderBy: z.union([UsuarioEmpresaOrderByWithAggregationInputObjectSchema, UsuarioEmpresaOrderByWithAggregationInputObjectSchema.array()]).optional(), having: UsuarioEmpresaScalarWhereWithAggregatesInputObjectSchema.optional(), take: z.number().optional(), skip: z.number().optional(), by: z.array(UsuarioEmpresaScalarFieldEnumSchema), _count: z.union([ z.literal(true), UsuarioEmpresaCountAggregateInputObjectSchema ]).optional(), _min: UsuarioEmpresaMinAggregateInputObjectSchema.optional(), _max: UsuarioEmpresaMaxAggregateInputObjectSchema.optional(), _avg: UsuarioEmpresaAvgAggregateInputObjectSchema.optional(), _sum: UsuarioEmpresaSumAggregateInputObjectSchema.optional() }).strict();