
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Actividad` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Actividad
 * 
 */
export type ActividadModel = runtime.Types.Result.DefaultSelection<Prisma.$ActividadPayload>

export type AggregateActividad = {
  _count: ActividadCountAggregateOutputType | null
  _avg: ActividadAvgAggregateOutputType | null
  _sum: ActividadSumAggregateOutputType | null
  _min: ActividadMinAggregateOutputType | null
  _max: ActividadMaxAggregateOutputType | null
}

export type ActividadAvgAggregateOutputType = {
  idActividad: number | null
  idEmpresa: number | null
}

export type ActividadSumAggregateOutputType = {
  idActividad: number | null
  idEmpresa: number | null
}

export type ActividadMinAggregateOutputType = {
  idActividad: number | null
  idEmpresa: number | null
  nombre: string | null
  inicio: Date | null
  fin: Date | null
  estado: string | null
  activa: boolean | null
}

export type ActividadMaxAggregateOutputType = {
  idActividad: number | null
  idEmpresa: number | null
  nombre: string | null
  inicio: Date | null
  fin: Date | null
  estado: string | null
  activa: boolean | null
}

export type ActividadCountAggregateOutputType = {
  idActividad: number
  idEmpresa: number
  nombre: number
  inicio: number
  fin: number
  estado: number
  activa: number
  _all: number
}


export type ActividadAvgAggregateInputType = {
  idActividad?: true
  idEmpresa?: true
}

export type ActividadSumAggregateInputType = {
  idActividad?: true
  idEmpresa?: true
}

export type ActividadMinAggregateInputType = {
  idActividad?: true
  idEmpresa?: true
  nombre?: true
  inicio?: true
  fin?: true
  estado?: true
  activa?: true
}

export type ActividadMaxAggregateInputType = {
  idActividad?: true
  idEmpresa?: true
  nombre?: true
  inicio?: true
  fin?: true
  estado?: true
  activa?: true
}

export type ActividadCountAggregateInputType = {
  idActividad?: true
  idEmpresa?: true
  nombre?: true
  inicio?: true
  fin?: true
  estado?: true
  activa?: true
  _all?: true
}

export type ActividadAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Actividad to aggregate.
   */
  where?: Prisma.ActividadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Actividads to fetch.
   */
  orderBy?: Prisma.ActividadOrderByWithRelationInput | Prisma.ActividadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ActividadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Actividads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Actividads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Actividads
  **/
  _count?: true | ActividadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ActividadAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ActividadSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActividadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActividadMaxAggregateInputType
}

export type GetActividadAggregateType<T extends ActividadAggregateArgs> = {
      [P in keyof T & keyof AggregateActividad]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActividad[P]>
    : Prisma.GetScalarType<T[P], AggregateActividad[P]>
}




export type ActividadGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ActividadWhereInput
  orderBy?: Prisma.ActividadOrderByWithAggregationInput | Prisma.ActividadOrderByWithAggregationInput[]
  by: Prisma.ActividadScalarFieldEnum[] | Prisma.ActividadScalarFieldEnum
  having?: Prisma.ActividadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActividadCountAggregateInputType | true
  _avg?: ActividadAvgAggregateInputType
  _sum?: ActividadSumAggregateInputType
  _min?: ActividadMinAggregateInputType
  _max?: ActividadMaxAggregateInputType
}

export type ActividadGroupByOutputType = {
  idActividad: number
  idEmpresa: number
  nombre: string
  inicio: Date
  fin: Date
  estado: string
  activa: boolean
  _count: ActividadCountAggregateOutputType | null
  _avg: ActividadAvgAggregateOutputType | null
  _sum: ActividadSumAggregateOutputType | null
  _min: ActividadMinAggregateOutputType | null
  _max: ActividadMaxAggregateOutputType | null
}

type GetActividadGroupByPayload<T extends ActividadGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActividadGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActividadGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActividadGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActividadGroupByOutputType[P]>
      }
    >
  >



export type ActividadWhereInput = {
  AND?: Prisma.ActividadWhereInput | Prisma.ActividadWhereInput[]
  OR?: Prisma.ActividadWhereInput[]
  NOT?: Prisma.ActividadWhereInput | Prisma.ActividadWhereInput[]
  idActividad?: Prisma.IntFilter<"Actividad"> | number
  idEmpresa?: Prisma.IntFilter<"Actividad"> | number
  nombre?: Prisma.StringFilter<"Actividad"> | string
  inicio?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  fin?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  estado?: Prisma.StringFilter<"Actividad"> | string
  activa?: Prisma.BoolFilter<"Actividad"> | boolean
  empresa?: Prisma.XOR<Prisma.EmpresasScalarRelationFilter, Prisma.EmpresasWhereInput>
  registros?: Prisma.RegistroListRelationFilter
}

export type ActividadOrderByWithRelationInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  activa?: Prisma.SortOrder
  empresa?: Prisma.EmpresasOrderByWithRelationInput
  registros?: Prisma.RegistroOrderByRelationAggregateInput
}

export type ActividadWhereUniqueInput = Prisma.AtLeast<{
  idActividad?: number
  AND?: Prisma.ActividadWhereInput | Prisma.ActividadWhereInput[]
  OR?: Prisma.ActividadWhereInput[]
  NOT?: Prisma.ActividadWhereInput | Prisma.ActividadWhereInput[]
  idEmpresa?: Prisma.IntFilter<"Actividad"> | number
  nombre?: Prisma.StringFilter<"Actividad"> | string
  inicio?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  fin?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  estado?: Prisma.StringFilter<"Actividad"> | string
  activa?: Prisma.BoolFilter<"Actividad"> | boolean
  empresa?: Prisma.XOR<Prisma.EmpresasScalarRelationFilter, Prisma.EmpresasWhereInput>
  registros?: Prisma.RegistroListRelationFilter
}, "idActividad">

export type ActividadOrderByWithAggregationInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  activa?: Prisma.SortOrder
  _count?: Prisma.ActividadCountOrderByAggregateInput
  _avg?: Prisma.ActividadAvgOrderByAggregateInput
  _max?: Prisma.ActividadMaxOrderByAggregateInput
  _min?: Prisma.ActividadMinOrderByAggregateInput
  _sum?: Prisma.ActividadSumOrderByAggregateInput
}

export type ActividadScalarWhereWithAggregatesInput = {
  AND?: Prisma.ActividadScalarWhereWithAggregatesInput | Prisma.ActividadScalarWhereWithAggregatesInput[]
  OR?: Prisma.ActividadScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ActividadScalarWhereWithAggregatesInput | Prisma.ActividadScalarWhereWithAggregatesInput[]
  idActividad?: Prisma.IntWithAggregatesFilter<"Actividad"> | number
  idEmpresa?: Prisma.IntWithAggregatesFilter<"Actividad"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Actividad"> | string
  inicio?: Prisma.DateTimeWithAggregatesFilter<"Actividad"> | Date | string
  fin?: Prisma.DateTimeWithAggregatesFilter<"Actividad"> | Date | string
  estado?: Prisma.StringWithAggregatesFilter<"Actividad"> | string
  activa?: Prisma.BoolWithAggregatesFilter<"Actividad"> | boolean
}

export type ActividadCreateInput = {
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
  empresa: Prisma.EmpresasCreateNestedOneWithoutActividadesInput
  registros?: Prisma.RegistroCreateNestedManyWithoutActividadInput
}

export type ActividadUncheckedCreateInput = {
  idActividad?: number
  idEmpresa: number
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
  registros?: Prisma.RegistroUncheckedCreateNestedManyWithoutActividadInput
}

export type ActividadUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
  empresa?: Prisma.EmpresasUpdateOneRequiredWithoutActividadesNestedInput
  registros?: Prisma.RegistroUpdateManyWithoutActividadNestedInput
}

export type ActividadUncheckedUpdateInput = {
  idActividad?: Prisma.IntFieldUpdateOperationsInput | number
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registros?: Prisma.RegistroUncheckedUpdateManyWithoutActividadNestedInput
}

export type ActividadCreateManyInput = {
  idActividad?: number
  idEmpresa: number
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
}

export type ActividadUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ActividadUncheckedUpdateManyInput = {
  idActividad?: Prisma.IntFieldUpdateOperationsInput | number
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ActividadListRelationFilter = {
  every?: Prisma.ActividadWhereInput
  some?: Prisma.ActividadWhereInput
  none?: Prisma.ActividadWhereInput
}

export type ActividadOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ActividadCountOrderByAggregateInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  activa?: Prisma.SortOrder
}

export type ActividadAvgOrderByAggregateInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type ActividadMaxOrderByAggregateInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  activa?: Prisma.SortOrder
}

export type ActividadMinOrderByAggregateInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  estado?: Prisma.SortOrder
  activa?: Prisma.SortOrder
}

export type ActividadSumOrderByAggregateInput = {
  idActividad?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type ActividadScalarRelationFilter = {
  is?: Prisma.ActividadWhereInput
  isNot?: Prisma.ActividadWhereInput
}

export type ActividadCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput> | Prisma.ActividadCreateWithoutEmpresaInput[] | Prisma.ActividadUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutEmpresaInput | Prisma.ActividadCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.ActividadCreateManyEmpresaInputEnvelope
  connect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
}

export type ActividadUncheckedCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput> | Prisma.ActividadCreateWithoutEmpresaInput[] | Prisma.ActividadUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutEmpresaInput | Prisma.ActividadCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.ActividadCreateManyEmpresaInputEnvelope
  connect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
}

export type ActividadUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput> | Prisma.ActividadCreateWithoutEmpresaInput[] | Prisma.ActividadUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutEmpresaInput | Prisma.ActividadCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.ActividadUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.ActividadUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.ActividadCreateManyEmpresaInputEnvelope
  set?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  disconnect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  delete?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  connect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  update?: Prisma.ActividadUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.ActividadUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.ActividadUpdateManyWithWhereWithoutEmpresaInput | Prisma.ActividadUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.ActividadScalarWhereInput | Prisma.ActividadScalarWhereInput[]
}

export type ActividadUncheckedUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput> | Prisma.ActividadCreateWithoutEmpresaInput[] | Prisma.ActividadUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutEmpresaInput | Prisma.ActividadCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.ActividadUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.ActividadUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.ActividadCreateManyEmpresaInputEnvelope
  set?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  disconnect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  delete?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  connect?: Prisma.ActividadWhereUniqueInput | Prisma.ActividadWhereUniqueInput[]
  update?: Prisma.ActividadUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.ActividadUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.ActividadUpdateManyWithWhereWithoutEmpresaInput | Prisma.ActividadUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.ActividadScalarWhereInput | Prisma.ActividadScalarWhereInput[]
}

export type ActividadCreateNestedOneWithoutRegistrosInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutRegistrosInput, Prisma.ActividadUncheckedCreateWithoutRegistrosInput>
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutRegistrosInput
  connect?: Prisma.ActividadWhereUniqueInput
}

export type ActividadUpdateOneRequiredWithoutRegistrosNestedInput = {
  create?: Prisma.XOR<Prisma.ActividadCreateWithoutRegistrosInput, Prisma.ActividadUncheckedCreateWithoutRegistrosInput>
  connectOrCreate?: Prisma.ActividadCreateOrConnectWithoutRegistrosInput
  upsert?: Prisma.ActividadUpsertWithoutRegistrosInput
  connect?: Prisma.ActividadWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ActividadUpdateToOneWithWhereWithoutRegistrosInput, Prisma.ActividadUpdateWithoutRegistrosInput>, Prisma.ActividadUncheckedUpdateWithoutRegistrosInput>
}

export type ActividadCreateWithoutEmpresaInput = {
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
  registros?: Prisma.RegistroCreateNestedManyWithoutActividadInput
}

export type ActividadUncheckedCreateWithoutEmpresaInput = {
  idActividad?: number
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
  registros?: Prisma.RegistroUncheckedCreateNestedManyWithoutActividadInput
}

export type ActividadCreateOrConnectWithoutEmpresaInput = {
  where: Prisma.ActividadWhereUniqueInput
  create: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput>
}

export type ActividadCreateManyEmpresaInputEnvelope = {
  data: Prisma.ActividadCreateManyEmpresaInput | Prisma.ActividadCreateManyEmpresaInput[]
  skipDuplicates?: boolean
}

export type ActividadUpsertWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.ActividadWhereUniqueInput
  update: Prisma.XOR<Prisma.ActividadUpdateWithoutEmpresaInput, Prisma.ActividadUncheckedUpdateWithoutEmpresaInput>
  create: Prisma.XOR<Prisma.ActividadCreateWithoutEmpresaInput, Prisma.ActividadUncheckedCreateWithoutEmpresaInput>
}

export type ActividadUpdateWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.ActividadWhereUniqueInput
  data: Prisma.XOR<Prisma.ActividadUpdateWithoutEmpresaInput, Prisma.ActividadUncheckedUpdateWithoutEmpresaInput>
}

export type ActividadUpdateManyWithWhereWithoutEmpresaInput = {
  where: Prisma.ActividadScalarWhereInput
  data: Prisma.XOR<Prisma.ActividadUpdateManyMutationInput, Prisma.ActividadUncheckedUpdateManyWithoutEmpresaInput>
}

export type ActividadScalarWhereInput = {
  AND?: Prisma.ActividadScalarWhereInput | Prisma.ActividadScalarWhereInput[]
  OR?: Prisma.ActividadScalarWhereInput[]
  NOT?: Prisma.ActividadScalarWhereInput | Prisma.ActividadScalarWhereInput[]
  idActividad?: Prisma.IntFilter<"Actividad"> | number
  idEmpresa?: Prisma.IntFilter<"Actividad"> | number
  nombre?: Prisma.StringFilter<"Actividad"> | string
  inicio?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  fin?: Prisma.DateTimeFilter<"Actividad"> | Date | string
  estado?: Prisma.StringFilter<"Actividad"> | string
  activa?: Prisma.BoolFilter<"Actividad"> | boolean
}

export type ActividadCreateWithoutRegistrosInput = {
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
  empresa: Prisma.EmpresasCreateNestedOneWithoutActividadesInput
}

export type ActividadUncheckedCreateWithoutRegistrosInput = {
  idActividad?: number
  idEmpresa: number
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
}

export type ActividadCreateOrConnectWithoutRegistrosInput = {
  where: Prisma.ActividadWhereUniqueInput
  create: Prisma.XOR<Prisma.ActividadCreateWithoutRegistrosInput, Prisma.ActividadUncheckedCreateWithoutRegistrosInput>
}

export type ActividadUpsertWithoutRegistrosInput = {
  update: Prisma.XOR<Prisma.ActividadUpdateWithoutRegistrosInput, Prisma.ActividadUncheckedUpdateWithoutRegistrosInput>
  create: Prisma.XOR<Prisma.ActividadCreateWithoutRegistrosInput, Prisma.ActividadUncheckedCreateWithoutRegistrosInput>
  where?: Prisma.ActividadWhereInput
}

export type ActividadUpdateToOneWithWhereWithoutRegistrosInput = {
  where?: Prisma.ActividadWhereInput
  data: Prisma.XOR<Prisma.ActividadUpdateWithoutRegistrosInput, Prisma.ActividadUncheckedUpdateWithoutRegistrosInput>
}

export type ActividadUpdateWithoutRegistrosInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
  empresa?: Prisma.EmpresasUpdateOneRequiredWithoutActividadesNestedInput
}

export type ActividadUncheckedUpdateWithoutRegistrosInput = {
  idActividad?: Prisma.IntFieldUpdateOperationsInput | number
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type ActividadCreateManyEmpresaInput = {
  idActividad?: number
  nombre: string
  inicio: Date | string
  fin: Date | string
  estado: string
  activa?: boolean
}

export type ActividadUpdateWithoutEmpresaInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registros?: Prisma.RegistroUpdateManyWithoutActividadNestedInput
}

export type ActividadUncheckedUpdateWithoutEmpresaInput = {
  idActividad?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
  registros?: Prisma.RegistroUncheckedUpdateManyWithoutActividadNestedInput
}

export type ActividadUncheckedUpdateManyWithoutEmpresaInput = {
  idActividad?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fin?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  estado?: Prisma.StringFieldUpdateOperationsInput | string
  activa?: Prisma.BoolFieldUpdateOperationsInput | boolean
}


/**
 * Count Type ActividadCountOutputType
 */

export type ActividadCountOutputType = {
  registros: number
}

export type ActividadCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  registros?: boolean | ActividadCountOutputTypeCountRegistrosArgs
}

/**
 * ActividadCountOutputType without action
 */
export type ActividadCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActividadCountOutputType
   */
  select?: Prisma.ActividadCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ActividadCountOutputType without action
 */
export type ActividadCountOutputTypeCountRegistrosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegistroWhereInput
}


export type ActividadSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idActividad?: boolean
  idEmpresa?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  estado?: boolean
  activa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
  registros?: boolean | Prisma.Actividad$registrosArgs<ExtArgs>
  _count?: boolean | Prisma.ActividadCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actividad"]>

export type ActividadSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idActividad?: boolean
  idEmpresa?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  estado?: boolean
  activa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actividad"]>

export type ActividadSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idActividad?: boolean
  idEmpresa?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  estado?: boolean
  activa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actividad"]>

export type ActividadSelectScalar = {
  idActividad?: boolean
  idEmpresa?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  estado?: boolean
  activa?: boolean
}

export type ActividadOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idActividad" | "idEmpresa" | "nombre" | "inicio" | "fin" | "estado" | "activa", ExtArgs["result"]["actividad"]>
export type ActividadInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
  registros?: boolean | Prisma.Actividad$registrosArgs<ExtArgs>
  _count?: boolean | Prisma.ActividadCountOutputTypeDefaultArgs<ExtArgs>
}
export type ActividadIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}
export type ActividadIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}

export type $ActividadPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Actividad"
  objects: {
    empresa: Prisma.$EmpresasPayload<ExtArgs>
    registros: Prisma.$RegistroPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idActividad: number
    idEmpresa: number
    nombre: string
    inicio: Date
    fin: Date
    estado: string
    activa: boolean
  }, ExtArgs["result"]["actividad"]>
  composites: {}
}

export type ActividadGetPayload<S extends boolean | null | undefined | ActividadDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ActividadPayload, S>

export type ActividadCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ActividadFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActividadCountAggregateInputType | true
  }

export interface ActividadDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Actividad'], meta: { name: 'Actividad' } }
  /**
   * Find zero or one Actividad that matches the filter.
   * @param {ActividadFindUniqueArgs} args - Arguments to find a Actividad
   * @example
   * // Get one Actividad
   * const actividad = await prisma.actividad.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ActividadFindUniqueArgs>(args: Prisma.SelectSubset<T, ActividadFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Actividad that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ActividadFindUniqueOrThrowArgs} args - Arguments to find a Actividad
   * @example
   * // Get one Actividad
   * const actividad = await prisma.actividad.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ActividadFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ActividadFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actividad that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadFindFirstArgs} args - Arguments to find a Actividad
   * @example
   * // Get one Actividad
   * const actividad = await prisma.actividad.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ActividadFindFirstArgs>(args?: Prisma.SelectSubset<T, ActividadFindFirstArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actividad that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadFindFirstOrThrowArgs} args - Arguments to find a Actividad
   * @example
   * // Get one Actividad
   * const actividad = await prisma.actividad.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ActividadFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ActividadFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Actividads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Actividads
   * const actividads = await prisma.actividad.findMany()
   * 
   * // Get first 10 Actividads
   * const actividads = await prisma.actividad.findMany({ take: 10 })
   * 
   * // Only select the `idActividad`
   * const actividadWithIdActividadOnly = await prisma.actividad.findMany({ select: { idActividad: true } })
   * 
   */
  findMany<T extends ActividadFindManyArgs>(args?: Prisma.SelectSubset<T, ActividadFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Actividad.
   * @param {ActividadCreateArgs} args - Arguments to create a Actividad.
   * @example
   * // Create one Actividad
   * const Actividad = await prisma.actividad.create({
   *   data: {
   *     // ... data to create a Actividad
   *   }
   * })
   * 
   */
  create<T extends ActividadCreateArgs>(args: Prisma.SelectSubset<T, ActividadCreateArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Actividads.
   * @param {ActividadCreateManyArgs} args - Arguments to create many Actividads.
   * @example
   * // Create many Actividads
   * const actividad = await prisma.actividad.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ActividadCreateManyArgs>(args?: Prisma.SelectSubset<T, ActividadCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Actividads and returns the data saved in the database.
   * @param {ActividadCreateManyAndReturnArgs} args - Arguments to create many Actividads.
   * @example
   * // Create many Actividads
   * const actividad = await prisma.actividad.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Actividads and only return the `idActividad`
   * const actividadWithIdActividadOnly = await prisma.actividad.createManyAndReturn({
   *   select: { idActividad: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ActividadCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ActividadCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Actividad.
   * @param {ActividadDeleteArgs} args - Arguments to delete one Actividad.
   * @example
   * // Delete one Actividad
   * const Actividad = await prisma.actividad.delete({
   *   where: {
   *     // ... filter to delete one Actividad
   *   }
   * })
   * 
   */
  delete<T extends ActividadDeleteArgs>(args: Prisma.SelectSubset<T, ActividadDeleteArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Actividad.
   * @param {ActividadUpdateArgs} args - Arguments to update one Actividad.
   * @example
   * // Update one Actividad
   * const actividad = await prisma.actividad.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ActividadUpdateArgs>(args: Prisma.SelectSubset<T, ActividadUpdateArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Actividads.
   * @param {ActividadDeleteManyArgs} args - Arguments to filter Actividads to delete.
   * @example
   * // Delete a few Actividads
   * const { count } = await prisma.actividad.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ActividadDeleteManyArgs>(args?: Prisma.SelectSubset<T, ActividadDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Actividads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Actividads
   * const actividad = await prisma.actividad.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ActividadUpdateManyArgs>(args: Prisma.SelectSubset<T, ActividadUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Actividads and returns the data updated in the database.
   * @param {ActividadUpdateManyAndReturnArgs} args - Arguments to update many Actividads.
   * @example
   * // Update many Actividads
   * const actividad = await prisma.actividad.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Actividads and only return the `idActividad`
   * const actividadWithIdActividadOnly = await prisma.actividad.updateManyAndReturn({
   *   select: { idActividad: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ActividadUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ActividadUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Actividad.
   * @param {ActividadUpsertArgs} args - Arguments to update or create a Actividad.
   * @example
   * // Update or create a Actividad
   * const actividad = await prisma.actividad.upsert({
   *   create: {
   *     // ... data to create a Actividad
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Actividad we want to update
   *   }
   * })
   */
  upsert<T extends ActividadUpsertArgs>(args: Prisma.SelectSubset<T, ActividadUpsertArgs<ExtArgs>>): Prisma.Prisma__ActividadClient<runtime.Types.Result.GetResult<Prisma.$ActividadPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Actividads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadCountArgs} args - Arguments to filter Actividads to count.
   * @example
   * // Count the number of Actividads
   * const count = await prisma.actividad.count({
   *   where: {
   *     // ... the filter for the Actividads we want to count
   *   }
   * })
  **/
  count<T extends ActividadCountArgs>(
    args?: Prisma.Subset<T, ActividadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActividadCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Actividad.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActividadAggregateArgs>(args: Prisma.Subset<T, ActividadAggregateArgs>): Prisma.PrismaPromise<GetActividadAggregateType<T>>

  /**
   * Group by Actividad.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActividadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ActividadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ActividadGroupByArgs['orderBy'] }
      : { orderBy?: ActividadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ActividadGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActividadGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Actividad model
 */
readonly fields: ActividadFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Actividad.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ActividadClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  empresa<T extends Prisma.EmpresasDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmpresasDefaultArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  registros<T extends Prisma.Actividad$registrosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Actividad$registrosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Actividad model
 */
export interface ActividadFieldRefs {
  readonly idActividad: Prisma.FieldRef<"Actividad", 'Int'>
  readonly idEmpresa: Prisma.FieldRef<"Actividad", 'Int'>
  readonly nombre: Prisma.FieldRef<"Actividad", 'String'>
  readonly inicio: Prisma.FieldRef<"Actividad", 'DateTime'>
  readonly fin: Prisma.FieldRef<"Actividad", 'DateTime'>
  readonly estado: Prisma.FieldRef<"Actividad", 'String'>
  readonly activa: Prisma.FieldRef<"Actividad", 'Boolean'>
}
    

// Custom InputTypes
/**
 * Actividad findUnique
 */
export type ActividadFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter, which Actividad to fetch.
   */
  where: Prisma.ActividadWhereUniqueInput
}

/**
 * Actividad findUniqueOrThrow
 */
export type ActividadFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter, which Actividad to fetch.
   */
  where: Prisma.ActividadWhereUniqueInput
}

/**
 * Actividad findFirst
 */
export type ActividadFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter, which Actividad to fetch.
   */
  where?: Prisma.ActividadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Actividads to fetch.
   */
  orderBy?: Prisma.ActividadOrderByWithRelationInput | Prisma.ActividadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Actividads.
   */
  cursor?: Prisma.ActividadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Actividads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Actividads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Actividads.
   */
  distinct?: Prisma.ActividadScalarFieldEnum | Prisma.ActividadScalarFieldEnum[]
}

/**
 * Actividad findFirstOrThrow
 */
export type ActividadFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter, which Actividad to fetch.
   */
  where?: Prisma.ActividadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Actividads to fetch.
   */
  orderBy?: Prisma.ActividadOrderByWithRelationInput | Prisma.ActividadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Actividads.
   */
  cursor?: Prisma.ActividadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Actividads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Actividads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Actividads.
   */
  distinct?: Prisma.ActividadScalarFieldEnum | Prisma.ActividadScalarFieldEnum[]
}

/**
 * Actividad findMany
 */
export type ActividadFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter, which Actividads to fetch.
   */
  where?: Prisma.ActividadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Actividads to fetch.
   */
  orderBy?: Prisma.ActividadOrderByWithRelationInput | Prisma.ActividadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Actividads.
   */
  cursor?: Prisma.ActividadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Actividads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Actividads.
   */
  skip?: number
  distinct?: Prisma.ActividadScalarFieldEnum | Prisma.ActividadScalarFieldEnum[]
}

/**
 * Actividad create
 */
export type ActividadCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * The data needed to create a Actividad.
   */
  data: Prisma.XOR<Prisma.ActividadCreateInput, Prisma.ActividadUncheckedCreateInput>
}

/**
 * Actividad createMany
 */
export type ActividadCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Actividads.
   */
  data: Prisma.ActividadCreateManyInput | Prisma.ActividadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Actividad createManyAndReturn
 */
export type ActividadCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * The data used to create many Actividads.
   */
  data: Prisma.ActividadCreateManyInput | Prisma.ActividadCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Actividad update
 */
export type ActividadUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * The data needed to update a Actividad.
   */
  data: Prisma.XOR<Prisma.ActividadUpdateInput, Prisma.ActividadUncheckedUpdateInput>
  /**
   * Choose, which Actividad to update.
   */
  where: Prisma.ActividadWhereUniqueInput
}

/**
 * Actividad updateMany
 */
export type ActividadUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Actividads.
   */
  data: Prisma.XOR<Prisma.ActividadUpdateManyMutationInput, Prisma.ActividadUncheckedUpdateManyInput>
  /**
   * Filter which Actividads to update
   */
  where?: Prisma.ActividadWhereInput
  /**
   * Limit how many Actividads to update.
   */
  limit?: number
}

/**
 * Actividad updateManyAndReturn
 */
export type ActividadUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * The data used to update Actividads.
   */
  data: Prisma.XOR<Prisma.ActividadUpdateManyMutationInput, Prisma.ActividadUncheckedUpdateManyInput>
  /**
   * Filter which Actividads to update
   */
  where?: Prisma.ActividadWhereInput
  /**
   * Limit how many Actividads to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Actividad upsert
 */
export type ActividadUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * The filter to search for the Actividad to update in case it exists.
   */
  where: Prisma.ActividadWhereUniqueInput
  /**
   * In case the Actividad found by the `where` argument doesn't exist, create a new Actividad with this data.
   */
  create: Prisma.XOR<Prisma.ActividadCreateInput, Prisma.ActividadUncheckedCreateInput>
  /**
   * In case the Actividad was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ActividadUpdateInput, Prisma.ActividadUncheckedUpdateInput>
}

/**
 * Actividad delete
 */
export type ActividadDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
  /**
   * Filter which Actividad to delete.
   */
  where: Prisma.ActividadWhereUniqueInput
}

/**
 * Actividad deleteMany
 */
export type ActividadDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Actividads to delete
   */
  where?: Prisma.ActividadWhereInput
  /**
   * Limit how many Actividads to delete.
   */
  limit?: number
}

/**
 * Actividad.registros
 */
export type Actividad$registrosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registro
   */
  select?: Prisma.RegistroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registro
   */
  omit?: Prisma.RegistroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistroInclude<ExtArgs> | null
  where?: Prisma.RegistroWhereInput
  orderBy?: Prisma.RegistroOrderByWithRelationInput | Prisma.RegistroOrderByWithRelationInput[]
  cursor?: Prisma.RegistroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RegistroScalarFieldEnum | Prisma.RegistroScalarFieldEnum[]
}

/**
 * Actividad without action
 */
export type ActividadDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Actividad
   */
  select?: Prisma.ActividadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Actividad
   */
  omit?: Prisma.ActividadOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ActividadInclude<ExtArgs> | null
}
