
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Talonarios` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Talonarios
 * 
 */
export type TalonariosModel = runtime.Types.Result.DefaultSelection<Prisma.$TalonariosPayload>

export type AggregateTalonarios = {
  _count: TalonariosCountAggregateOutputType | null
  _avg: TalonariosAvgAggregateOutputType | null
  _sum: TalonariosSumAggregateOutputType | null
  _min: TalonariosMinAggregateOutputType | null
  _max: TalonariosMaxAggregateOutputType | null
}

export type TalonariosAvgAggregateOutputType = {
  idTalon: number | null
  inicio: number | null
  fin: number | null
  actual: number | null
}

export type TalonariosSumAggregateOutputType = {
  idTalon: number | null
  inicio: number | null
  fin: number | null
  actual: number | null
}

export type TalonariosMinAggregateOutputType = {
  idTalon: number | null
  nombre: string | null
  inicio: number | null
  fin: number | null
  actual: number | null
}

export type TalonariosMaxAggregateOutputType = {
  idTalon: number | null
  nombre: string | null
  inicio: number | null
  fin: number | null
  actual: number | null
}

export type TalonariosCountAggregateOutputType = {
  idTalon: number
  nombre: number
  inicio: number
  fin: number
  actual: number
  _all: number
}


export type TalonariosAvgAggregateInputType = {
  idTalon?: true
  inicio?: true
  fin?: true
  actual?: true
}

export type TalonariosSumAggregateInputType = {
  idTalon?: true
  inicio?: true
  fin?: true
  actual?: true
}

export type TalonariosMinAggregateInputType = {
  idTalon?: true
  nombre?: true
  inicio?: true
  fin?: true
  actual?: true
}

export type TalonariosMaxAggregateInputType = {
  idTalon?: true
  nombre?: true
  inicio?: true
  fin?: true
  actual?: true
}

export type TalonariosCountAggregateInputType = {
  idTalon?: true
  nombre?: true
  inicio?: true
  fin?: true
  actual?: true
  _all?: true
}

export type TalonariosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Talonarios to aggregate.
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Talonarios to fetch.
   */
  orderBy?: Prisma.TalonariosOrderByWithRelationInput | Prisma.TalonariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.TalonariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Talonarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Talonarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Talonarios
  **/
  _count?: true | TalonariosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TalonariosAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TalonariosSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TalonariosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TalonariosMaxAggregateInputType
}

export type GetTalonariosAggregateType<T extends TalonariosAggregateArgs> = {
      [P in keyof T & keyof AggregateTalonarios]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTalonarios[P]>
    : Prisma.GetScalarType<T[P], AggregateTalonarios[P]>
}




export type TalonariosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TalonariosWhereInput
  orderBy?: Prisma.TalonariosOrderByWithAggregationInput | Prisma.TalonariosOrderByWithAggregationInput[]
  by: Prisma.TalonariosScalarFieldEnum[] | Prisma.TalonariosScalarFieldEnum
  having?: Prisma.TalonariosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TalonariosCountAggregateInputType | true
  _avg?: TalonariosAvgAggregateInputType
  _sum?: TalonariosSumAggregateInputType
  _min?: TalonariosMinAggregateInputType
  _max?: TalonariosMaxAggregateInputType
}

export type TalonariosGroupByOutputType = {
  idTalon: number
  nombre: string
  inicio: number
  fin: number
  actual: number
  _count: TalonariosCountAggregateOutputType | null
  _avg: TalonariosAvgAggregateOutputType | null
  _sum: TalonariosSumAggregateOutputType | null
  _min: TalonariosMinAggregateOutputType | null
  _max: TalonariosMaxAggregateOutputType | null
}

type GetTalonariosGroupByPayload<T extends TalonariosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TalonariosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TalonariosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TalonariosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TalonariosGroupByOutputType[P]>
      }
    >
  >



export type TalonariosWhereInput = {
  AND?: Prisma.TalonariosWhereInput | Prisma.TalonariosWhereInput[]
  OR?: Prisma.TalonariosWhereInput[]
  NOT?: Prisma.TalonariosWhereInput | Prisma.TalonariosWhereInput[]
  idTalon?: Prisma.IntFilter<"Talonarios"> | number
  nombre?: Prisma.StringFilter<"Talonarios"> | string
  inicio?: Prisma.IntFilter<"Talonarios"> | number
  fin?: Prisma.IntFilter<"Talonarios"> | number
  actual?: Prisma.IntFilter<"Talonarios"> | number
  tiposDoc?: Prisma.TiposDocListRelationFilter
}

export type TalonariosOrderByWithRelationInput = {
  idTalon?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
  tiposDoc?: Prisma.TiposDocOrderByRelationAggregateInput
}

export type TalonariosWhereUniqueInput = Prisma.AtLeast<{
  idTalon?: number
  AND?: Prisma.TalonariosWhereInput | Prisma.TalonariosWhereInput[]
  OR?: Prisma.TalonariosWhereInput[]
  NOT?: Prisma.TalonariosWhereInput | Prisma.TalonariosWhereInput[]
  nombre?: Prisma.StringFilter<"Talonarios"> | string
  inicio?: Prisma.IntFilter<"Talonarios"> | number
  fin?: Prisma.IntFilter<"Talonarios"> | number
  actual?: Prisma.IntFilter<"Talonarios"> | number
  tiposDoc?: Prisma.TiposDocListRelationFilter
}, "idTalon">

export type TalonariosOrderByWithAggregationInput = {
  idTalon?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
  _count?: Prisma.TalonariosCountOrderByAggregateInput
  _avg?: Prisma.TalonariosAvgOrderByAggregateInput
  _max?: Prisma.TalonariosMaxOrderByAggregateInput
  _min?: Prisma.TalonariosMinOrderByAggregateInput
  _sum?: Prisma.TalonariosSumOrderByAggregateInput
}

export type TalonariosScalarWhereWithAggregatesInput = {
  AND?: Prisma.TalonariosScalarWhereWithAggregatesInput | Prisma.TalonariosScalarWhereWithAggregatesInput[]
  OR?: Prisma.TalonariosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.TalonariosScalarWhereWithAggregatesInput | Prisma.TalonariosScalarWhereWithAggregatesInput[]
  idTalon?: Prisma.IntWithAggregatesFilter<"Talonarios"> | number
  nombre?: Prisma.StringWithAggregatesFilter<"Talonarios"> | string
  inicio?: Prisma.IntWithAggregatesFilter<"Talonarios"> | number
  fin?: Prisma.IntWithAggregatesFilter<"Talonarios"> | number
  actual?: Prisma.IntWithAggregatesFilter<"Talonarios"> | number
}

export type TalonariosCreateInput = {
  nombre: string
  inicio: number
  fin: number
  actual: number
  tiposDoc?: Prisma.TiposDocCreateNestedManyWithoutTalonarioInput
}

export type TalonariosUncheckedCreateInput = {
  idTalon?: number
  nombre: string
  inicio: number
  fin: number
  actual: number
  tiposDoc?: Prisma.TiposDocUncheckedCreateNestedManyWithoutTalonarioInput
}

export type TalonariosUpdateInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
  tiposDoc?: Prisma.TiposDocUpdateManyWithoutTalonarioNestedInput
}

export type TalonariosUncheckedUpdateInput = {
  idTalon?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
  tiposDoc?: Prisma.TiposDocUncheckedUpdateManyWithoutTalonarioNestedInput
}

export type TalonariosCreateManyInput = {
  idTalon?: number
  nombre: string
  inicio: number
  fin: number
  actual: number
}

export type TalonariosUpdateManyMutationInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TalonariosUncheckedUpdateManyInput = {
  idTalon?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TalonariosCountOrderByAggregateInput = {
  idTalon?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
}

export type TalonariosAvgOrderByAggregateInput = {
  idTalon?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
}

export type TalonariosMaxOrderByAggregateInput = {
  idTalon?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
}

export type TalonariosMinOrderByAggregateInput = {
  idTalon?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
}

export type TalonariosSumOrderByAggregateInput = {
  idTalon?: Prisma.SortOrder
  inicio?: Prisma.SortOrder
  fin?: Prisma.SortOrder
  actual?: Prisma.SortOrder
}

export type TalonariosNullableScalarRelationFilter = {
  is?: Prisma.TalonariosWhereInput | null
  isNot?: Prisma.TalonariosWhereInput | null
}

export type TalonariosCreateNestedOneWithoutTiposDocInput = {
  create?: Prisma.XOR<Prisma.TalonariosCreateWithoutTiposDocInput, Prisma.TalonariosUncheckedCreateWithoutTiposDocInput>
  connectOrCreate?: Prisma.TalonariosCreateOrConnectWithoutTiposDocInput
  connect?: Prisma.TalonariosWhereUniqueInput
}

export type TalonariosUpdateOneWithoutTiposDocNestedInput = {
  create?: Prisma.XOR<Prisma.TalonariosCreateWithoutTiposDocInput, Prisma.TalonariosUncheckedCreateWithoutTiposDocInput>
  connectOrCreate?: Prisma.TalonariosCreateOrConnectWithoutTiposDocInput
  upsert?: Prisma.TalonariosUpsertWithoutTiposDocInput
  disconnect?: Prisma.TalonariosWhereInput | boolean
  delete?: Prisma.TalonariosWhereInput | boolean
  connect?: Prisma.TalonariosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.TalonariosUpdateToOneWithWhereWithoutTiposDocInput, Prisma.TalonariosUpdateWithoutTiposDocInput>, Prisma.TalonariosUncheckedUpdateWithoutTiposDocInput>
}

export type TalonariosCreateWithoutTiposDocInput = {
  nombre: string
  inicio: number
  fin: number
  actual: number
}

export type TalonariosUncheckedCreateWithoutTiposDocInput = {
  idTalon?: number
  nombre: string
  inicio: number
  fin: number
  actual: number
}

export type TalonariosCreateOrConnectWithoutTiposDocInput = {
  where: Prisma.TalonariosWhereUniqueInput
  create: Prisma.XOR<Prisma.TalonariosCreateWithoutTiposDocInput, Prisma.TalonariosUncheckedCreateWithoutTiposDocInput>
}

export type TalonariosUpsertWithoutTiposDocInput = {
  update: Prisma.XOR<Prisma.TalonariosUpdateWithoutTiposDocInput, Prisma.TalonariosUncheckedUpdateWithoutTiposDocInput>
  create: Prisma.XOR<Prisma.TalonariosCreateWithoutTiposDocInput, Prisma.TalonariosUncheckedCreateWithoutTiposDocInput>
  where?: Prisma.TalonariosWhereInput
}

export type TalonariosUpdateToOneWithWhereWithoutTiposDocInput = {
  where?: Prisma.TalonariosWhereInput
  data: Prisma.XOR<Prisma.TalonariosUpdateWithoutTiposDocInput, Prisma.TalonariosUncheckedUpdateWithoutTiposDocInput>
}

export type TalonariosUpdateWithoutTiposDocInput = {
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TalonariosUncheckedUpdateWithoutTiposDocInput = {
  idTalon?: Prisma.IntFieldUpdateOperationsInput | number
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  inicio?: Prisma.IntFieldUpdateOperationsInput | number
  fin?: Prisma.IntFieldUpdateOperationsInput | number
  actual?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type TalonariosCountOutputType
 */

export type TalonariosCountOutputType = {
  tiposDoc: number
}

export type TalonariosCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tiposDoc?: boolean | TalonariosCountOutputTypeCountTiposDocArgs
}

/**
 * TalonariosCountOutputType without action
 */
export type TalonariosCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TalonariosCountOutputType
   */
  select?: Prisma.TalonariosCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TalonariosCountOutputType without action
 */
export type TalonariosCountOutputTypeCountTiposDocArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.TiposDocWhereInput
}


export type TalonariosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idTalon?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  actual?: boolean
  tiposDoc?: boolean | Prisma.Talonarios$tiposDocArgs<ExtArgs>
  _count?: boolean | Prisma.TalonariosCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["talonarios"]>

export type TalonariosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idTalon?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  actual?: boolean
}, ExtArgs["result"]["talonarios"]>

export type TalonariosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idTalon?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  actual?: boolean
}, ExtArgs["result"]["talonarios"]>

export type TalonariosSelectScalar = {
  idTalon?: boolean
  nombre?: boolean
  inicio?: boolean
  fin?: boolean
  actual?: boolean
}

export type TalonariosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idTalon" | "nombre" | "inicio" | "fin" | "actual", ExtArgs["result"]["talonarios"]>
export type TalonariosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  tiposDoc?: boolean | Prisma.Talonarios$tiposDocArgs<ExtArgs>
  _count?: boolean | Prisma.TalonariosCountOutputTypeDefaultArgs<ExtArgs>
}
export type TalonariosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type TalonariosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $TalonariosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Talonarios"
  objects: {
    tiposDoc: Prisma.$TiposDocPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idTalon: number
    nombre: string
    inicio: number
    fin: number
    actual: number
  }, ExtArgs["result"]["talonarios"]>
  composites: {}
}

export type TalonariosGetPayload<S extends boolean | null | undefined | TalonariosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TalonariosPayload, S>

export type TalonariosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<TalonariosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TalonariosCountAggregateInputType | true
  }

export interface TalonariosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Talonarios'], meta: { name: 'Talonarios' } }
  /**
   * Find zero or one Talonarios that matches the filter.
   * @param {TalonariosFindUniqueArgs} args - Arguments to find a Talonarios
   * @example
   * // Get one Talonarios
   * const talonarios = await prisma.talonarios.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends TalonariosFindUniqueArgs>(args: Prisma.SelectSubset<T, TalonariosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Talonarios that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {TalonariosFindUniqueOrThrowArgs} args - Arguments to find a Talonarios
   * @example
   * // Get one Talonarios
   * const talonarios = await prisma.talonarios.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends TalonariosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, TalonariosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Talonarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosFindFirstArgs} args - Arguments to find a Talonarios
   * @example
   * // Get one Talonarios
   * const talonarios = await prisma.talonarios.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends TalonariosFindFirstArgs>(args?: Prisma.SelectSubset<T, TalonariosFindFirstArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Talonarios that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosFindFirstOrThrowArgs} args - Arguments to find a Talonarios
   * @example
   * // Get one Talonarios
   * const talonarios = await prisma.talonarios.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends TalonariosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, TalonariosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Talonarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Talonarios
   * const talonarios = await prisma.talonarios.findMany()
   * 
   * // Get first 10 Talonarios
   * const talonarios = await prisma.talonarios.findMany({ take: 10 })
   * 
   * // Only select the `idTalon`
   * const talonariosWithIdTalonOnly = await prisma.talonarios.findMany({ select: { idTalon: true } })
   * 
   */
  findMany<T extends TalonariosFindManyArgs>(args?: Prisma.SelectSubset<T, TalonariosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Talonarios.
   * @param {TalonariosCreateArgs} args - Arguments to create a Talonarios.
   * @example
   * // Create one Talonarios
   * const Talonarios = await prisma.talonarios.create({
   *   data: {
   *     // ... data to create a Talonarios
   *   }
   * })
   * 
   */
  create<T extends TalonariosCreateArgs>(args: Prisma.SelectSubset<T, TalonariosCreateArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Talonarios.
   * @param {TalonariosCreateManyArgs} args - Arguments to create many Talonarios.
   * @example
   * // Create many Talonarios
   * const talonarios = await prisma.talonarios.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends TalonariosCreateManyArgs>(args?: Prisma.SelectSubset<T, TalonariosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Talonarios and returns the data saved in the database.
   * @param {TalonariosCreateManyAndReturnArgs} args - Arguments to create many Talonarios.
   * @example
   * // Create many Talonarios
   * const talonarios = await prisma.talonarios.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Talonarios and only return the `idTalon`
   * const talonariosWithIdTalonOnly = await prisma.talonarios.createManyAndReturn({
   *   select: { idTalon: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends TalonariosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, TalonariosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Talonarios.
   * @param {TalonariosDeleteArgs} args - Arguments to delete one Talonarios.
   * @example
   * // Delete one Talonarios
   * const Talonarios = await prisma.talonarios.delete({
   *   where: {
   *     // ... filter to delete one Talonarios
   *   }
   * })
   * 
   */
  delete<T extends TalonariosDeleteArgs>(args: Prisma.SelectSubset<T, TalonariosDeleteArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Talonarios.
   * @param {TalonariosUpdateArgs} args - Arguments to update one Talonarios.
   * @example
   * // Update one Talonarios
   * const talonarios = await prisma.talonarios.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends TalonariosUpdateArgs>(args: Prisma.SelectSubset<T, TalonariosUpdateArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Talonarios.
   * @param {TalonariosDeleteManyArgs} args - Arguments to filter Talonarios to delete.
   * @example
   * // Delete a few Talonarios
   * const { count } = await prisma.talonarios.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends TalonariosDeleteManyArgs>(args?: Prisma.SelectSubset<T, TalonariosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Talonarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Talonarios
   * const talonarios = await prisma.talonarios.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends TalonariosUpdateManyArgs>(args: Prisma.SelectSubset<T, TalonariosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Talonarios and returns the data updated in the database.
   * @param {TalonariosUpdateManyAndReturnArgs} args - Arguments to update many Talonarios.
   * @example
   * // Update many Talonarios
   * const talonarios = await prisma.talonarios.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Talonarios and only return the `idTalon`
   * const talonariosWithIdTalonOnly = await prisma.talonarios.updateManyAndReturn({
   *   select: { idTalon: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends TalonariosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, TalonariosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Talonarios.
   * @param {TalonariosUpsertArgs} args - Arguments to update or create a Talonarios.
   * @example
   * // Update or create a Talonarios
   * const talonarios = await prisma.talonarios.upsert({
   *   create: {
   *     // ... data to create a Talonarios
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Talonarios we want to update
   *   }
   * })
   */
  upsert<T extends TalonariosUpsertArgs>(args: Prisma.SelectSubset<T, TalonariosUpsertArgs<ExtArgs>>): Prisma.Prisma__TalonariosClient<runtime.Types.Result.GetResult<Prisma.$TalonariosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Talonarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosCountArgs} args - Arguments to filter Talonarios to count.
   * @example
   * // Count the number of Talonarios
   * const count = await prisma.talonarios.count({
   *   where: {
   *     // ... the filter for the Talonarios we want to count
   *   }
   * })
  **/
  count<T extends TalonariosCountArgs>(
    args?: Prisma.Subset<T, TalonariosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TalonariosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Talonarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TalonariosAggregateArgs>(args: Prisma.Subset<T, TalonariosAggregateArgs>): Prisma.PrismaPromise<GetTalonariosAggregateType<T>>

  /**
   * Group by Talonarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TalonariosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends TalonariosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: TalonariosGroupByArgs['orderBy'] }
      : { orderBy?: TalonariosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, TalonariosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTalonariosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Talonarios model
 */
readonly fields: TalonariosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Talonarios.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__TalonariosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  tiposDoc<T extends Prisma.Talonarios$tiposDocArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Talonarios$tiposDocArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$TiposDocPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Talonarios model
 */
export interface TalonariosFieldRefs {
  readonly idTalon: Prisma.FieldRef<"Talonarios", 'Int'>
  readonly nombre: Prisma.FieldRef<"Talonarios", 'String'>
  readonly inicio: Prisma.FieldRef<"Talonarios", 'Int'>
  readonly fin: Prisma.FieldRef<"Talonarios", 'Int'>
  readonly actual: Prisma.FieldRef<"Talonarios", 'Int'>
}
    

// Custom InputTypes
/**
 * Talonarios findUnique
 */
export type TalonariosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter, which Talonarios to fetch.
   */
  where: Prisma.TalonariosWhereUniqueInput
}

/**
 * Talonarios findUniqueOrThrow
 */
export type TalonariosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter, which Talonarios to fetch.
   */
  where: Prisma.TalonariosWhereUniqueInput
}

/**
 * Talonarios findFirst
 */
export type TalonariosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter, which Talonarios to fetch.
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Talonarios to fetch.
   */
  orderBy?: Prisma.TalonariosOrderByWithRelationInput | Prisma.TalonariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Talonarios.
   */
  cursor?: Prisma.TalonariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Talonarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Talonarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Talonarios.
   */
  distinct?: Prisma.TalonariosScalarFieldEnum | Prisma.TalonariosScalarFieldEnum[]
}

/**
 * Talonarios findFirstOrThrow
 */
export type TalonariosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter, which Talonarios to fetch.
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Talonarios to fetch.
   */
  orderBy?: Prisma.TalonariosOrderByWithRelationInput | Prisma.TalonariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Talonarios.
   */
  cursor?: Prisma.TalonariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Talonarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Talonarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Talonarios.
   */
  distinct?: Prisma.TalonariosScalarFieldEnum | Prisma.TalonariosScalarFieldEnum[]
}

/**
 * Talonarios findMany
 */
export type TalonariosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter, which Talonarios to fetch.
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Talonarios to fetch.
   */
  orderBy?: Prisma.TalonariosOrderByWithRelationInput | Prisma.TalonariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Talonarios.
   */
  cursor?: Prisma.TalonariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Talonarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Talonarios.
   */
  skip?: number
  distinct?: Prisma.TalonariosScalarFieldEnum | Prisma.TalonariosScalarFieldEnum[]
}

/**
 * Talonarios create
 */
export type TalonariosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * The data needed to create a Talonarios.
   */
  data: Prisma.XOR<Prisma.TalonariosCreateInput, Prisma.TalonariosUncheckedCreateInput>
}

/**
 * Talonarios createMany
 */
export type TalonariosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Talonarios.
   */
  data: Prisma.TalonariosCreateManyInput | Prisma.TalonariosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Talonarios createManyAndReturn
 */
export type TalonariosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * The data used to create many Talonarios.
   */
  data: Prisma.TalonariosCreateManyInput | Prisma.TalonariosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Talonarios update
 */
export type TalonariosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * The data needed to update a Talonarios.
   */
  data: Prisma.XOR<Prisma.TalonariosUpdateInput, Prisma.TalonariosUncheckedUpdateInput>
  /**
   * Choose, which Talonarios to update.
   */
  where: Prisma.TalonariosWhereUniqueInput
}

/**
 * Talonarios updateMany
 */
export type TalonariosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Talonarios.
   */
  data: Prisma.XOR<Prisma.TalonariosUpdateManyMutationInput, Prisma.TalonariosUncheckedUpdateManyInput>
  /**
   * Filter which Talonarios to update
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * Limit how many Talonarios to update.
   */
  limit?: number
}

/**
 * Talonarios updateManyAndReturn
 */
export type TalonariosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * The data used to update Talonarios.
   */
  data: Prisma.XOR<Prisma.TalonariosUpdateManyMutationInput, Prisma.TalonariosUncheckedUpdateManyInput>
  /**
   * Filter which Talonarios to update
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * Limit how many Talonarios to update.
   */
  limit?: number
}

/**
 * Talonarios upsert
 */
export type TalonariosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * The filter to search for the Talonarios to update in case it exists.
   */
  where: Prisma.TalonariosWhereUniqueInput
  /**
   * In case the Talonarios found by the `where` argument doesn't exist, create a new Talonarios with this data.
   */
  create: Prisma.XOR<Prisma.TalonariosCreateInput, Prisma.TalonariosUncheckedCreateInput>
  /**
   * In case the Talonarios was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.TalonariosUpdateInput, Prisma.TalonariosUncheckedUpdateInput>
}

/**
 * Talonarios delete
 */
export type TalonariosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
  /**
   * Filter which Talonarios to delete.
   */
  where: Prisma.TalonariosWhereUniqueInput
}

/**
 * Talonarios deleteMany
 */
export type TalonariosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Talonarios to delete
   */
  where?: Prisma.TalonariosWhereInput
  /**
   * Limit how many Talonarios to delete.
   */
  limit?: number
}

/**
 * Talonarios.tiposDoc
 */
export type Talonarios$tiposDocArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TiposDoc
   */
  select?: Prisma.TiposDocSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TiposDoc
   */
  omit?: Prisma.TiposDocOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TiposDocInclude<ExtArgs> | null
  where?: Prisma.TiposDocWhereInput
  orderBy?: Prisma.TiposDocOrderByWithRelationInput | Prisma.TiposDocOrderByWithRelationInput[]
  cursor?: Prisma.TiposDocWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TiposDocScalarFieldEnum | Prisma.TiposDocScalarFieldEnum[]
}

/**
 * Talonarios without action
 */
export type TalonariosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Talonarios
   */
  select?: Prisma.TalonariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Talonarios
   */
  omit?: Prisma.TalonariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.TalonariosInclude<ExtArgs> | null
}
