
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Usuarios` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model Usuarios
 * 
 */
export type UsuariosModel = runtime.Types.Result.DefaultSelection<Prisma.$UsuariosPayload>

export type AggregateUsuarios = {
  _count: UsuariosCountAggregateOutputType | null
  _avg: UsuariosAvgAggregateOutputType | null
  _sum: UsuariosSumAggregateOutputType | null
  _min: UsuariosMinAggregateOutputType | null
  _max: UsuariosMaxAggregateOutputType | null
}

export type UsuariosAvgAggregateOutputType = {
  idUsuario: number | null
  idEmpresa: number | null
}

export type UsuariosSumAggregateOutputType = {
  idUsuario: number | null
  idEmpresa: number | null
}

export type UsuariosMinAggregateOutputType = {
  idUsuario: number | null
  username: string | null
  email: string | null
  password: string | null
  nombre: string | null
  activo: boolean | null
  creadoEn: Date | null
  actualizadoEn: Date | null
  idEmpresa: number | null
}

export type UsuariosMaxAggregateOutputType = {
  idUsuario: number | null
  username: string | null
  email: string | null
  password: string | null
  nombre: string | null
  activo: boolean | null
  creadoEn: Date | null
  actualizadoEn: Date | null
  idEmpresa: number | null
}

export type UsuariosCountAggregateOutputType = {
  idUsuario: number
  username: number
  email: number
  password: number
  nombre: number
  activo: number
  creadoEn: number
  actualizadoEn: number
  idEmpresa: number
  _all: number
}


export type UsuariosAvgAggregateInputType = {
  idUsuario?: true
  idEmpresa?: true
}

export type UsuariosSumAggregateInputType = {
  idUsuario?: true
  idEmpresa?: true
}

export type UsuariosMinAggregateInputType = {
  idUsuario?: true
  username?: true
  email?: true
  password?: true
  nombre?: true
  activo?: true
  creadoEn?: true
  actualizadoEn?: true
  idEmpresa?: true
}

export type UsuariosMaxAggregateInputType = {
  idUsuario?: true
  username?: true
  email?: true
  password?: true
  nombre?: true
  activo?: true
  creadoEn?: true
  actualizadoEn?: true
  idEmpresa?: true
}

export type UsuariosCountAggregateInputType = {
  idUsuario?: true
  username?: true
  email?: true
  password?: true
  nombre?: true
  activo?: true
  creadoEn?: true
  actualizadoEn?: true
  idEmpresa?: true
  _all?: true
}

export type UsuariosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Usuarios to aggregate.
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuariosOrderByWithRelationInput | Prisma.UsuariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.UsuariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Usuarios
  **/
  _count?: true | UsuariosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: UsuariosAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: UsuariosSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: UsuariosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: UsuariosMaxAggregateInputType
}

export type GetUsuariosAggregateType<T extends UsuariosAggregateArgs> = {
      [P in keyof T & keyof AggregateUsuarios]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateUsuarios[P]>
    : Prisma.GetScalarType<T[P], AggregateUsuarios[P]>
}




export type UsuariosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.UsuariosWhereInput
  orderBy?: Prisma.UsuariosOrderByWithAggregationInput | Prisma.UsuariosOrderByWithAggregationInput[]
  by: Prisma.UsuariosScalarFieldEnum[] | Prisma.UsuariosScalarFieldEnum
  having?: Prisma.UsuariosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: UsuariosCountAggregateInputType | true
  _avg?: UsuariosAvgAggregateInputType
  _sum?: UsuariosSumAggregateInputType
  _min?: UsuariosMinAggregateInputType
  _max?: UsuariosMaxAggregateInputType
}

export type UsuariosGroupByOutputType = {
  idUsuario: number
  username: string
  email: string
  password: string
  nombre: string
  activo: boolean
  creadoEn: Date
  actualizadoEn: Date
  idEmpresa: number
  _count: UsuariosCountAggregateOutputType | null
  _avg: UsuariosAvgAggregateOutputType | null
  _sum: UsuariosSumAggregateOutputType | null
  _min: UsuariosMinAggregateOutputType | null
  _max: UsuariosMaxAggregateOutputType | null
}

type GetUsuariosGroupByPayload<T extends UsuariosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<UsuariosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof UsuariosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], UsuariosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], UsuariosGroupByOutputType[P]>
      }
    >
  >



export type UsuariosWhereInput = {
  AND?: Prisma.UsuariosWhereInput | Prisma.UsuariosWhereInput[]
  OR?: Prisma.UsuariosWhereInput[]
  NOT?: Prisma.UsuariosWhereInput | Prisma.UsuariosWhereInput[]
  idUsuario?: Prisma.IntFilter<"Usuarios"> | number
  username?: Prisma.StringFilter<"Usuarios"> | string
  email?: Prisma.StringFilter<"Usuarios"> | string
  password?: Prisma.StringFilter<"Usuarios"> | string
  nombre?: Prisma.StringFilter<"Usuarios"> | string
  activo?: Prisma.BoolFilter<"Usuarios"> | boolean
  creadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  actualizadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  idEmpresa?: Prisma.IntFilter<"Usuarios"> | number
  empresa?: Prisma.XOR<Prisma.EmpresasScalarRelationFilter, Prisma.EmpresasWhereInput>
  registros?: Prisma.RegistroListRelationFilter
}

export type UsuariosOrderByWithRelationInput = {
  idUsuario?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  actualizadoEn?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  empresa?: Prisma.EmpresasOrderByWithRelationInput
  registros?: Prisma.RegistroOrderByRelationAggregateInput
}

export type UsuariosWhereUniqueInput = Prisma.AtLeast<{
  idUsuario?: number
  username?: string
  email?: string
  AND?: Prisma.UsuariosWhereInput | Prisma.UsuariosWhereInput[]
  OR?: Prisma.UsuariosWhereInput[]
  NOT?: Prisma.UsuariosWhereInput | Prisma.UsuariosWhereInput[]
  password?: Prisma.StringFilter<"Usuarios"> | string
  nombre?: Prisma.StringFilter<"Usuarios"> | string
  activo?: Prisma.BoolFilter<"Usuarios"> | boolean
  creadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  actualizadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  idEmpresa?: Prisma.IntFilter<"Usuarios"> | number
  empresa?: Prisma.XOR<Prisma.EmpresasScalarRelationFilter, Prisma.EmpresasWhereInput>
  registros?: Prisma.RegistroListRelationFilter
}, "idUsuario" | "username" | "email">

export type UsuariosOrderByWithAggregationInput = {
  idUsuario?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  actualizadoEn?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
  _count?: Prisma.UsuariosCountOrderByAggregateInput
  _avg?: Prisma.UsuariosAvgOrderByAggregateInput
  _max?: Prisma.UsuariosMaxOrderByAggregateInput
  _min?: Prisma.UsuariosMinOrderByAggregateInput
  _sum?: Prisma.UsuariosSumOrderByAggregateInput
}

export type UsuariosScalarWhereWithAggregatesInput = {
  AND?: Prisma.UsuariosScalarWhereWithAggregatesInput | Prisma.UsuariosScalarWhereWithAggregatesInput[]
  OR?: Prisma.UsuariosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.UsuariosScalarWhereWithAggregatesInput | Prisma.UsuariosScalarWhereWithAggregatesInput[]
  idUsuario?: Prisma.IntWithAggregatesFilter<"Usuarios"> | number
  username?: Prisma.StringWithAggregatesFilter<"Usuarios"> | string
  email?: Prisma.StringWithAggregatesFilter<"Usuarios"> | string
  password?: Prisma.StringWithAggregatesFilter<"Usuarios"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"Usuarios"> | string
  activo?: Prisma.BoolWithAggregatesFilter<"Usuarios"> | boolean
  creadoEn?: Prisma.DateTimeWithAggregatesFilter<"Usuarios"> | Date | string
  actualizadoEn?: Prisma.DateTimeWithAggregatesFilter<"Usuarios"> | Date | string
  idEmpresa?: Prisma.IntWithAggregatesFilter<"Usuarios"> | number
}

export type UsuariosCreateInput = {
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  empresa: Prisma.EmpresasCreateNestedOneWithoutUsuariosInput
  registros?: Prisma.RegistroCreateNestedManyWithoutUsuarioInput
}

export type UsuariosUncheckedCreateInput = {
  idUsuario?: number
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  idEmpresa: number
  registros?: Prisma.RegistroUncheckedCreateNestedManyWithoutUsuarioInput
}

export type UsuariosUpdateInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  empresa?: Prisma.EmpresasUpdateOneRequiredWithoutUsuariosNestedInput
  registros?: Prisma.RegistroUpdateManyWithoutUsuarioNestedInput
}

export type UsuariosUncheckedUpdateInput = {
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
  registros?: Prisma.RegistroUncheckedUpdateManyWithoutUsuarioNestedInput
}

export type UsuariosCreateManyInput = {
  idUsuario?: number
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  idEmpresa: number
}

export type UsuariosUpdateManyMutationInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type UsuariosUncheckedUpdateManyInput = {
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UsuariosCountOrderByAggregateInput = {
  idUsuario?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  actualizadoEn?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type UsuariosAvgOrderByAggregateInput = {
  idUsuario?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type UsuariosMaxOrderByAggregateInput = {
  idUsuario?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  actualizadoEn?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type UsuariosMinOrderByAggregateInput = {
  idUsuario?: Prisma.SortOrder
  username?: Prisma.SortOrder
  email?: Prisma.SortOrder
  password?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  creadoEn?: Prisma.SortOrder
  actualizadoEn?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type UsuariosSumOrderByAggregateInput = {
  idUsuario?: Prisma.SortOrder
  idEmpresa?: Prisma.SortOrder
}

export type UsuariosListRelationFilter = {
  every?: Prisma.UsuariosWhereInput
  some?: Prisma.UsuariosWhereInput
  none?: Prisma.UsuariosWhereInput
}

export type UsuariosOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type UsuariosScalarRelationFilter = {
  is?: Prisma.UsuariosWhereInput
  isNot?: Prisma.UsuariosWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type UsuariosCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput> | Prisma.UsuariosCreateWithoutEmpresaInput[] | Prisma.UsuariosUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutEmpresaInput | Prisma.UsuariosCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.UsuariosCreateManyEmpresaInputEnvelope
  connect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
}

export type UsuariosUncheckedCreateNestedManyWithoutEmpresaInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput> | Prisma.UsuariosCreateWithoutEmpresaInput[] | Prisma.UsuariosUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutEmpresaInput | Prisma.UsuariosCreateOrConnectWithoutEmpresaInput[]
  createMany?: Prisma.UsuariosCreateManyEmpresaInputEnvelope
  connect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
}

export type UsuariosUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput> | Prisma.UsuariosCreateWithoutEmpresaInput[] | Prisma.UsuariosUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutEmpresaInput | Prisma.UsuariosCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.UsuariosUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.UsuariosUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.UsuariosCreateManyEmpresaInputEnvelope
  set?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  disconnect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  delete?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  connect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  update?: Prisma.UsuariosUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.UsuariosUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.UsuariosUpdateManyWithWhereWithoutEmpresaInput | Prisma.UsuariosUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.UsuariosScalarWhereInput | Prisma.UsuariosScalarWhereInput[]
}

export type UsuariosUncheckedUpdateManyWithoutEmpresaNestedInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput> | Prisma.UsuariosCreateWithoutEmpresaInput[] | Prisma.UsuariosUncheckedCreateWithoutEmpresaInput[]
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutEmpresaInput | Prisma.UsuariosCreateOrConnectWithoutEmpresaInput[]
  upsert?: Prisma.UsuariosUpsertWithWhereUniqueWithoutEmpresaInput | Prisma.UsuariosUpsertWithWhereUniqueWithoutEmpresaInput[]
  createMany?: Prisma.UsuariosCreateManyEmpresaInputEnvelope
  set?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  disconnect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  delete?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  connect?: Prisma.UsuariosWhereUniqueInput | Prisma.UsuariosWhereUniqueInput[]
  update?: Prisma.UsuariosUpdateWithWhereUniqueWithoutEmpresaInput | Prisma.UsuariosUpdateWithWhereUniqueWithoutEmpresaInput[]
  updateMany?: Prisma.UsuariosUpdateManyWithWhereWithoutEmpresaInput | Prisma.UsuariosUpdateManyWithWhereWithoutEmpresaInput[]
  deleteMany?: Prisma.UsuariosScalarWhereInput | Prisma.UsuariosScalarWhereInput[]
}

export type UsuariosCreateNestedOneWithoutRegistrosInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutRegistrosInput, Prisma.UsuariosUncheckedCreateWithoutRegistrosInput>
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutRegistrosInput
  connect?: Prisma.UsuariosWhereUniqueInput
}

export type UsuariosUpdateOneRequiredWithoutRegistrosNestedInput = {
  create?: Prisma.XOR<Prisma.UsuariosCreateWithoutRegistrosInput, Prisma.UsuariosUncheckedCreateWithoutRegistrosInput>
  connectOrCreate?: Prisma.UsuariosCreateOrConnectWithoutRegistrosInput
  upsert?: Prisma.UsuariosUpsertWithoutRegistrosInput
  connect?: Prisma.UsuariosWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.UsuariosUpdateToOneWithWhereWithoutRegistrosInput, Prisma.UsuariosUpdateWithoutRegistrosInput>, Prisma.UsuariosUncheckedUpdateWithoutRegistrosInput>
}

export type UsuariosCreateWithoutEmpresaInput = {
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  registros?: Prisma.RegistroCreateNestedManyWithoutUsuarioInput
}

export type UsuariosUncheckedCreateWithoutEmpresaInput = {
  idUsuario?: number
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  registros?: Prisma.RegistroUncheckedCreateNestedManyWithoutUsuarioInput
}

export type UsuariosCreateOrConnectWithoutEmpresaInput = {
  where: Prisma.UsuariosWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput>
}

export type UsuariosCreateManyEmpresaInputEnvelope = {
  data: Prisma.UsuariosCreateManyEmpresaInput | Prisma.UsuariosCreateManyEmpresaInput[]
  skipDuplicates?: boolean
}

export type UsuariosUpsertWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.UsuariosWhereUniqueInput
  update: Prisma.XOR<Prisma.UsuariosUpdateWithoutEmpresaInput, Prisma.UsuariosUncheckedUpdateWithoutEmpresaInput>
  create: Prisma.XOR<Prisma.UsuariosCreateWithoutEmpresaInput, Prisma.UsuariosUncheckedCreateWithoutEmpresaInput>
}

export type UsuariosUpdateWithWhereUniqueWithoutEmpresaInput = {
  where: Prisma.UsuariosWhereUniqueInput
  data: Prisma.XOR<Prisma.UsuariosUpdateWithoutEmpresaInput, Prisma.UsuariosUncheckedUpdateWithoutEmpresaInput>
}

export type UsuariosUpdateManyWithWhereWithoutEmpresaInput = {
  where: Prisma.UsuariosScalarWhereInput
  data: Prisma.XOR<Prisma.UsuariosUpdateManyMutationInput, Prisma.UsuariosUncheckedUpdateManyWithoutEmpresaInput>
}

export type UsuariosScalarWhereInput = {
  AND?: Prisma.UsuariosScalarWhereInput | Prisma.UsuariosScalarWhereInput[]
  OR?: Prisma.UsuariosScalarWhereInput[]
  NOT?: Prisma.UsuariosScalarWhereInput | Prisma.UsuariosScalarWhereInput[]
  idUsuario?: Prisma.IntFilter<"Usuarios"> | number
  username?: Prisma.StringFilter<"Usuarios"> | string
  email?: Prisma.StringFilter<"Usuarios"> | string
  password?: Prisma.StringFilter<"Usuarios"> | string
  nombre?: Prisma.StringFilter<"Usuarios"> | string
  activo?: Prisma.BoolFilter<"Usuarios"> | boolean
  creadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  actualizadoEn?: Prisma.DateTimeFilter<"Usuarios"> | Date | string
  idEmpresa?: Prisma.IntFilter<"Usuarios"> | number
}

export type UsuariosCreateWithoutRegistrosInput = {
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  empresa: Prisma.EmpresasCreateNestedOneWithoutUsuariosInput
}

export type UsuariosUncheckedCreateWithoutRegistrosInput = {
  idUsuario?: number
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
  idEmpresa: number
}

export type UsuariosCreateOrConnectWithoutRegistrosInput = {
  where: Prisma.UsuariosWhereUniqueInput
  create: Prisma.XOR<Prisma.UsuariosCreateWithoutRegistrosInput, Prisma.UsuariosUncheckedCreateWithoutRegistrosInput>
}

export type UsuariosUpsertWithoutRegistrosInput = {
  update: Prisma.XOR<Prisma.UsuariosUpdateWithoutRegistrosInput, Prisma.UsuariosUncheckedUpdateWithoutRegistrosInput>
  create: Prisma.XOR<Prisma.UsuariosCreateWithoutRegistrosInput, Prisma.UsuariosUncheckedCreateWithoutRegistrosInput>
  where?: Prisma.UsuariosWhereInput
}

export type UsuariosUpdateToOneWithWhereWithoutRegistrosInput = {
  where?: Prisma.UsuariosWhereInput
  data: Prisma.XOR<Prisma.UsuariosUpdateWithoutRegistrosInput, Prisma.UsuariosUncheckedUpdateWithoutRegistrosInput>
}

export type UsuariosUpdateWithoutRegistrosInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  empresa?: Prisma.EmpresasUpdateOneRequiredWithoutUsuariosNestedInput
}

export type UsuariosUncheckedUpdateWithoutRegistrosInput = {
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  idEmpresa?: Prisma.IntFieldUpdateOperationsInput | number
}

export type UsuariosCreateManyEmpresaInput = {
  idUsuario?: number
  username: string
  email: string
  password: string
  nombre: string
  activo?: boolean
  creadoEn?: Date | string
  actualizadoEn?: Date | string
}

export type UsuariosUpdateWithoutEmpresaInput = {
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registros?: Prisma.RegistroUpdateManyWithoutUsuarioNestedInput
}

export type UsuariosUncheckedUpdateWithoutEmpresaInput = {
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  registros?: Prisma.RegistroUncheckedUpdateManyWithoutUsuarioNestedInput
}

export type UsuariosUncheckedUpdateManyWithoutEmpresaInput = {
  idUsuario?: Prisma.IntFieldUpdateOperationsInput | number
  username?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.StringFieldUpdateOperationsInput | string
  password?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.BoolFieldUpdateOperationsInput | boolean
  creadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  actualizadoEn?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type UsuariosCountOutputType
 */

export type UsuariosCountOutputType = {
  registros: number
}

export type UsuariosCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  registros?: boolean | UsuariosCountOutputTypeCountRegistrosArgs
}

/**
 * UsuariosCountOutputType without action
 */
export type UsuariosCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the UsuariosCountOutputType
   */
  select?: Prisma.UsuariosCountOutputTypeSelect<ExtArgs> | null
}

/**
 * UsuariosCountOutputType without action
 */
export type UsuariosCountOutputTypeCountRegistrosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RegistroWhereInput
}


export type UsuariosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idUsuario?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  nombre?: boolean
  activo?: boolean
  creadoEn?: boolean
  actualizadoEn?: boolean
  idEmpresa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
  registros?: boolean | Prisma.Usuarios$registrosArgs<ExtArgs>
  _count?: boolean | Prisma.UsuariosCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuarios"]>

export type UsuariosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idUsuario?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  nombre?: boolean
  activo?: boolean
  creadoEn?: boolean
  actualizadoEn?: boolean
  idEmpresa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuarios"]>

export type UsuariosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  idUsuario?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  nombre?: boolean
  activo?: boolean
  creadoEn?: boolean
  actualizadoEn?: boolean
  idEmpresa?: boolean
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}, ExtArgs["result"]["usuarios"]>

export type UsuariosSelectScalar = {
  idUsuario?: boolean
  username?: boolean
  email?: boolean
  password?: boolean
  nombre?: boolean
  activo?: boolean
  creadoEn?: boolean
  actualizadoEn?: boolean
  idEmpresa?: boolean
}

export type UsuariosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"idUsuario" | "username" | "email" | "password" | "nombre" | "activo" | "creadoEn" | "actualizadoEn" | "idEmpresa", ExtArgs["result"]["usuarios"]>
export type UsuariosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
  registros?: boolean | Prisma.Usuarios$registrosArgs<ExtArgs>
  _count?: boolean | Prisma.UsuariosCountOutputTypeDefaultArgs<ExtArgs>
}
export type UsuariosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}
export type UsuariosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  empresa?: boolean | Prisma.EmpresasDefaultArgs<ExtArgs>
}

export type $UsuariosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Usuarios"
  objects: {
    empresa: Prisma.$EmpresasPayload<ExtArgs>
    registros: Prisma.$RegistroPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    idUsuario: number
    username: string
    email: string
    password: string
    nombre: string
    activo: boolean
    creadoEn: Date
    actualizadoEn: Date
    idEmpresa: number
  }, ExtArgs["result"]["usuarios"]>
  composites: {}
}

export type UsuariosGetPayload<S extends boolean | null | undefined | UsuariosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$UsuariosPayload, S>

export type UsuariosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<UsuariosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: UsuariosCountAggregateInputType | true
  }

export interface UsuariosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Usuarios'], meta: { name: 'Usuarios' } }
  /**
   * Find zero or one Usuarios that matches the filter.
   * @param {UsuariosFindUniqueArgs} args - Arguments to find a Usuarios
   * @example
   * // Get one Usuarios
   * const usuarios = await prisma.usuarios.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends UsuariosFindUniqueArgs>(args: Prisma.SelectSubset<T, UsuariosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Usuarios that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {UsuariosFindUniqueOrThrowArgs} args - Arguments to find a Usuarios
   * @example
   * // Get one Usuarios
   * const usuarios = await prisma.usuarios.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends UsuariosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, UsuariosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Usuarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosFindFirstArgs} args - Arguments to find a Usuarios
   * @example
   * // Get one Usuarios
   * const usuarios = await prisma.usuarios.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends UsuariosFindFirstArgs>(args?: Prisma.SelectSubset<T, UsuariosFindFirstArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Usuarios that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosFindFirstOrThrowArgs} args - Arguments to find a Usuarios
   * @example
   * // Get one Usuarios
   * const usuarios = await prisma.usuarios.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends UsuariosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, UsuariosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Usuarios that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Usuarios
   * const usuarios = await prisma.usuarios.findMany()
   * 
   * // Get first 10 Usuarios
   * const usuarios = await prisma.usuarios.findMany({ take: 10 })
   * 
   * // Only select the `idUsuario`
   * const usuariosWithIdUsuarioOnly = await prisma.usuarios.findMany({ select: { idUsuario: true } })
   * 
   */
  findMany<T extends UsuariosFindManyArgs>(args?: Prisma.SelectSubset<T, UsuariosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Usuarios.
   * @param {UsuariosCreateArgs} args - Arguments to create a Usuarios.
   * @example
   * // Create one Usuarios
   * const Usuarios = await prisma.usuarios.create({
   *   data: {
   *     // ... data to create a Usuarios
   *   }
   * })
   * 
   */
  create<T extends UsuariosCreateArgs>(args: Prisma.SelectSubset<T, UsuariosCreateArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Usuarios.
   * @param {UsuariosCreateManyArgs} args - Arguments to create many Usuarios.
   * @example
   * // Create many Usuarios
   * const usuarios = await prisma.usuarios.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends UsuariosCreateManyArgs>(args?: Prisma.SelectSubset<T, UsuariosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Usuarios and returns the data saved in the database.
   * @param {UsuariosCreateManyAndReturnArgs} args - Arguments to create many Usuarios.
   * @example
   * // Create many Usuarios
   * const usuarios = await prisma.usuarios.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Usuarios and only return the `idUsuario`
   * const usuariosWithIdUsuarioOnly = await prisma.usuarios.createManyAndReturn({
   *   select: { idUsuario: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends UsuariosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, UsuariosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Usuarios.
   * @param {UsuariosDeleteArgs} args - Arguments to delete one Usuarios.
   * @example
   * // Delete one Usuarios
   * const Usuarios = await prisma.usuarios.delete({
   *   where: {
   *     // ... filter to delete one Usuarios
   *   }
   * })
   * 
   */
  delete<T extends UsuariosDeleteArgs>(args: Prisma.SelectSubset<T, UsuariosDeleteArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Usuarios.
   * @param {UsuariosUpdateArgs} args - Arguments to update one Usuarios.
   * @example
   * // Update one Usuarios
   * const usuarios = await prisma.usuarios.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends UsuariosUpdateArgs>(args: Prisma.SelectSubset<T, UsuariosUpdateArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Usuarios.
   * @param {UsuariosDeleteManyArgs} args - Arguments to filter Usuarios to delete.
   * @example
   * // Delete a few Usuarios
   * const { count } = await prisma.usuarios.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends UsuariosDeleteManyArgs>(args?: Prisma.SelectSubset<T, UsuariosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Usuarios
   * const usuarios = await prisma.usuarios.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends UsuariosUpdateManyArgs>(args: Prisma.SelectSubset<T, UsuariosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Usuarios and returns the data updated in the database.
   * @param {UsuariosUpdateManyAndReturnArgs} args - Arguments to update many Usuarios.
   * @example
   * // Update many Usuarios
   * const usuarios = await prisma.usuarios.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Usuarios and only return the `idUsuario`
   * const usuariosWithIdUsuarioOnly = await prisma.usuarios.updateManyAndReturn({
   *   select: { idUsuario: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends UsuariosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, UsuariosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Usuarios.
   * @param {UsuariosUpsertArgs} args - Arguments to update or create a Usuarios.
   * @example
   * // Update or create a Usuarios
   * const usuarios = await prisma.usuarios.upsert({
   *   create: {
   *     // ... data to create a Usuarios
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Usuarios we want to update
   *   }
   * })
   */
  upsert<T extends UsuariosUpsertArgs>(args: Prisma.SelectSubset<T, UsuariosUpsertArgs<ExtArgs>>): Prisma.Prisma__UsuariosClient<runtime.Types.Result.GetResult<Prisma.$UsuariosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosCountArgs} args - Arguments to filter Usuarios to count.
   * @example
   * // Count the number of Usuarios
   * const count = await prisma.usuarios.count({
   *   where: {
   *     // ... the filter for the Usuarios we want to count
   *   }
   * })
  **/
  count<T extends UsuariosCountArgs>(
    args?: Prisma.Subset<T, UsuariosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], UsuariosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends UsuariosAggregateArgs>(args: Prisma.Subset<T, UsuariosAggregateArgs>): Prisma.PrismaPromise<GetUsuariosAggregateType<T>>

  /**
   * Group by Usuarios.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {UsuariosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends UsuariosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: UsuariosGroupByArgs['orderBy'] }
      : { orderBy?: UsuariosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, UsuariosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetUsuariosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Usuarios model
 */
readonly fields: UsuariosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Usuarios.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__UsuariosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  empresa<T extends Prisma.EmpresasDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EmpresasDefaultArgs<ExtArgs>>): Prisma.Prisma__EmpresasClient<runtime.Types.Result.GetResult<Prisma.$EmpresasPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  registros<T extends Prisma.Usuarios$registrosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Usuarios$registrosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RegistroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Usuarios model
 */
export interface UsuariosFieldRefs {
  readonly idUsuario: Prisma.FieldRef<"Usuarios", 'Int'>
  readonly username: Prisma.FieldRef<"Usuarios", 'String'>
  readonly email: Prisma.FieldRef<"Usuarios", 'String'>
  readonly password: Prisma.FieldRef<"Usuarios", 'String'>
  readonly nombre: Prisma.FieldRef<"Usuarios", 'String'>
  readonly activo: Prisma.FieldRef<"Usuarios", 'Boolean'>
  readonly creadoEn: Prisma.FieldRef<"Usuarios", 'DateTime'>
  readonly actualizadoEn: Prisma.FieldRef<"Usuarios", 'DateTime'>
  readonly idEmpresa: Prisma.FieldRef<"Usuarios", 'Int'>
}
    

// Custom InputTypes
/**
 * Usuarios findUnique
 */
export type UsuariosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where: Prisma.UsuariosWhereUniqueInput
}

/**
 * Usuarios findUniqueOrThrow
 */
export type UsuariosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where: Prisma.UsuariosWhereUniqueInput
}

/**
 * Usuarios findFirst
 */
export type UsuariosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuariosOrderByWithRelationInput | Prisma.UsuariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usuarios.
   */
  cursor?: Prisma.UsuariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usuarios.
   */
  distinct?: Prisma.UsuariosScalarFieldEnum | Prisma.UsuariosScalarFieldEnum[]
}

/**
 * Usuarios findFirstOrThrow
 */
export type UsuariosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuariosOrderByWithRelationInput | Prisma.UsuariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Usuarios.
   */
  cursor?: Prisma.UsuariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Usuarios.
   */
  distinct?: Prisma.UsuariosScalarFieldEnum | Prisma.UsuariosScalarFieldEnum[]
}

/**
 * Usuarios findMany
 */
export type UsuariosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter, which Usuarios to fetch.
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Usuarios to fetch.
   */
  orderBy?: Prisma.UsuariosOrderByWithRelationInput | Prisma.UsuariosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Usuarios.
   */
  cursor?: Prisma.UsuariosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Usuarios from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Usuarios.
   */
  skip?: number
  distinct?: Prisma.UsuariosScalarFieldEnum | Prisma.UsuariosScalarFieldEnum[]
}

/**
 * Usuarios create
 */
export type UsuariosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * The data needed to create a Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuariosCreateInput, Prisma.UsuariosUncheckedCreateInput>
}

/**
 * Usuarios createMany
 */
export type UsuariosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Usuarios.
   */
  data: Prisma.UsuariosCreateManyInput | Prisma.UsuariosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Usuarios createManyAndReturn
 */
export type UsuariosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * The data used to create many Usuarios.
   */
  data: Prisma.UsuariosCreateManyInput | Prisma.UsuariosCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Usuarios update
 */
export type UsuariosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * The data needed to update a Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuariosUpdateInput, Prisma.UsuariosUncheckedUpdateInput>
  /**
   * Choose, which Usuarios to update.
   */
  where: Prisma.UsuariosWhereUniqueInput
}

/**
 * Usuarios updateMany
 */
export type UsuariosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuariosUpdateManyMutationInput, Prisma.UsuariosUncheckedUpdateManyInput>
  /**
   * Filter which Usuarios to update
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * Limit how many Usuarios to update.
   */
  limit?: number
}

/**
 * Usuarios updateManyAndReturn
 */
export type UsuariosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * The data used to update Usuarios.
   */
  data: Prisma.XOR<Prisma.UsuariosUpdateManyMutationInput, Prisma.UsuariosUncheckedUpdateManyInput>
  /**
   * Filter which Usuarios to update
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * Limit how many Usuarios to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Usuarios upsert
 */
export type UsuariosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * The filter to search for the Usuarios to update in case it exists.
   */
  where: Prisma.UsuariosWhereUniqueInput
  /**
   * In case the Usuarios found by the `where` argument doesn't exist, create a new Usuarios with this data.
   */
  create: Prisma.XOR<Prisma.UsuariosCreateInput, Prisma.UsuariosUncheckedCreateInput>
  /**
   * In case the Usuarios was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.UsuariosUpdateInput, Prisma.UsuariosUncheckedUpdateInput>
}

/**
 * Usuarios delete
 */
export type UsuariosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
  /**
   * Filter which Usuarios to delete.
   */
  where: Prisma.UsuariosWhereUniqueInput
}

/**
 * Usuarios deleteMany
 */
export type UsuariosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Usuarios to delete
   */
  where?: Prisma.UsuariosWhereInput
  /**
   * Limit how many Usuarios to delete.
   */
  limit?: number
}

/**
 * Usuarios.registros
 */
export type Usuarios$registrosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Registro
   */
  select?: Prisma.RegistroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Registro
   */
  omit?: Prisma.RegistroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RegistroInclude<ExtArgs> | null
  where?: Prisma.RegistroWhereInput
  orderBy?: Prisma.RegistroOrderByWithRelationInput | Prisma.RegistroOrderByWithRelationInput[]
  cursor?: Prisma.RegistroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RegistroScalarFieldEnum | Prisma.RegistroScalarFieldEnum[]
}

/**
 * Usuarios without action
 */
export type UsuariosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Usuarios
   */
  select?: Prisma.UsuariosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Usuarios
   */
  omit?: Prisma.UsuariosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UsuariosInclude<ExtArgs> | null
}
