openapi: 3.0.3
info:
  title: Auth API
  version: "1.0.0"
servers:
  - url: http://localhost:{PORT}
    variables:
      PORT:
        default: "3000"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /login:
    post:
      tags: [Public]
      summary: Autentica un usuario y devuelve un JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
      responses:
        "200":
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                required: [message, user, token]
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    required: [id, username, email, nombre, rol]
                    properties:
                      id: { type: integer }
                      username: { type: string }
                      email: { type: string, format: email }
                      nombre: { type: string }
                      rol:
                        type: string
                        enum: [ADMIN, USER]
                  token:
                    type: string
                  expiresIn:
                    type: integer
                    description: Tiempo en segundos hasta que el token expira
        "400":
          description: Body inválido / validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
        "401":
          description: Credenciales inválidas
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
  /register:
    post:
      tags: [Public]
      summary: Registra un usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, email, password, nombre]
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                nombre:
                  type: string
                  minLength: 2
                  maxLength: 80
      responses:
        "201":
          description: Usuario USER (requiere activación)
          content:
            application/json:
              schema:
                type: object
                required: [message, user]
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    required: [id, username, email, nombre, rol]
                    properties:
                      id: { type: integer }
                      username: { type: string }
                      email: { type: string, format: email }
                      nombre: { type: string }
                      rol:
                        type: string
                        enum: [ADMIN, USER]
        "400":
          description: Body inválido / validación
          content:
            application/json:
              schema:
                type: object
                properties:
                  message: { type: string }
  /auth/activate:
    get:
      tags: [Public]
      summary: Activa una cuenta de usuario
      description: Activa la cuenta usando un token enviado por email
      parameters:
        - in: query
          name: token
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Cuenta activada
        "400":
          description: Token inválido o expirado
  /auth/resend-activation:
    post:
      tags: [Public]
      summary: Reenvía email de activación
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email]
              properties:
                email:
                  type: string
                  format: email
      responses:
        "200":
          description: Respuesta genérica (no revela existencia del email)
/auth/reset-password/request:
  post:
    tags: [Public]
    summary: Solicita reset de contraseña
    description: |
      Envia un correo con un token para restablecer la contraseña.
      La respuesta siempre es genérica para no revelar si el email existe.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required: [email]
            properties:
              email:
                type: string
                format: email
                example: usuario@ejemplo.com
    responses:
      "200":
        description: Correo de reset enviado (respuesta genérica)
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: "Si el email existe, se enviará un correo."
  /auth/reset-password:
    post:
      tags: [Public]
      summary: Cambia la contraseña usando token
      description: |
        Actualiza la contraseña de un usuario. El token debe ser válido y no haber expirado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [token, passwordNueva]
              properties:
                token:
                  type: string
                  minLength: 20
                  example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                passwordNueva:
                  type: string
                  minLength: 8
                  example: "NuevaContraseña123!"
      responses:
        "200":
          description: Contraseña actualizada correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Contraseña actualizada correctamente"
        "400":
          description: Token inválido o expirado / Request inválido
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Token inválido o expirado"
